      implicit double precision (a-h,o-z)
      character txt300*300, txt300c*300, let*1, txt4*4, txt4a*4, let1*1
      character txtksy(10)*150, txt150*150
      character cmmnd*110
      character drctry*15, zgDatFile*50

      logical strcon, idluni

      INTEGER DEBSTR,FINSTR
      character typ2*12
      parameter(pi=3.14159265359,c=2.99792458d8, deg2rd=pi/180.d0)
      parameter(zero=0.d0)

      data typ2 / 'intrinsic' /
      data am, q, G / 938.27203d6,1.602176487d-19,1.7928474d0 /
      data x0, xp0, y0, yp0, s0, dpp0 / 0.d0,0.d0,0.d0,0.d0,0.d0,0.d0 /
      data nTrj, ddp, Dx, Dxp / 1, 1.d-3, 0.d0, 0.d0 /
     
       
C Get particle data, for spin, from spinN0FIT.In
      if (idluni(lunR)) then
        open(unit=lunR,file='spinN0FIT.In'
     >                ,status='old',err=999)
        read(lunR,*)  am, q, G
      endif

C Now build zgoubi.dat from zgoubi_spinN0FIT-In.dat
      if (idluni(lunR)) then
        open(unit=lunR,file='zgoubi_spinN0FIT-In.dat'
     >                ,status='old',err=95)
        rewind(lunR)
      endif
      if (idluni(lunW)) then
        open(unit=lunW,file='zgoubi_searchCO-In.dat')
        rewind(lunW)
      endif

C Read in zgoubi_spinN0FIT-In.dat
        read(lunR,fmt='(a)') txt300       ! title
        write(lunW,fmt='(a)') 'Data generated by  spinN0FIT '
          read(lunR,fmt='(a)') txt300     ! (MC)OBJET
          write(lunW,*) '''OBJET'''
          read(lunR,fmt='(a)') txt300     ! BORO
          write(lunW,*) txt300(debstr(txt300):finstr(txt300))
C Remove all the rest of objet
 2    continue
        read(lunR,fmt='(a)') txt300       
        if(txt300(debstr(txt300):debstr(txt300)).ne.'''') goto 2
        backspace(lunR)

C Create KOBJ=2 type of object --------------------
      write(lunW,*) '2'
      write(lunW,*) nTrj, '   1'
      k10 = nTrj/10
      kk = nTrj - 10*k10
      iTrj = -dble((nTrj-1)/2)
 3    continue
      dpp = dpp0 + dble(iTrj)*ddp
      write(lunW,fmt='(1p,4(1x,e14.6),a,1e14.6,3x,a3)') 
     > x0+Dx*dpp,xp0+Dx*dpp,y0,yp0,' 0. ',1.d0+dpp,'''a'''
      iTrj = iTrj + 1
      if(iTrj.le.dble((nTrj-1)/2)) goto 3     
      txt300 = '1 1 1 1 1 1 1 1 1 1 '
      do ii = 1, k10
        write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      enddo
      if(kk.ne.0) write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
C--------------------------------------------------
C Place pick-ups here, used by searchCO_short
      txt300 = '''PICKUPS'''
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      txt300 = '   1        '
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      txt300 = '   #Start '
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      txt300 = '''MARKER''   #Start '
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))

C Complete zgoubi.dat from content of zgoubi_spinN0FIT-In.dat
 1      continue
          read(lunR,fmt='(a)',end=13) txt300
          txt300 = txt300(debstr(txt300):132)

          if(strcon(txt300,'''FAISCEAU''',10,
     >                                           IS)) then 

          elseif(strcon(txt300,'''SPNTRK''',8,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300
            if(txt300(debstr(txt300):debstr(txt300)) .eq. '''') 
     >        write(lunW,*) txt300(debstr(txt300):finstr(txt300))

          elseif(strcon(txt300,'''PICKUPS''',9,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''SPNSTORE''',10,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''FAISTORE''',10,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''FAISCNL''',9,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''SPNPRNL''',9,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''MARKER''',8,
     >                                        IS)) then 
            txt300c = txt300(IS+8:132-8)
            txt300c = txt300c(debstr(txt300c):debstr(txt300c)+6)
            if(txt300c.eq.'#Start') then
            elseif(txt300c.eq.'#End') then
            else              
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            endif

          elseif(strcon(txt300,'''CAVITE''',8,
     >                                        IS)) then
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              read(lunR,fmt='(a)',end=13) txt300
              write(lunW,*) ' 0 '//txt300(debstr(txt300):finstr(txt300))
              read(lunR,fmt='(a)',end=13) txt300
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              read(lunR,fmt='(a)',end=13) txt300
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))

          elseif(strcon(txt300,'''REBELOTE''',10,
     >                                         IS)) then
            goto 11

          elseif(strcon(txt300,'''TWISS''',7,
     >                                         IS)) then
            read(lunR,fmt='(a)',end=13) txt300

          elseif(strcon(txt300,'''FIT''',5,
     >                                       IS)
     >      .or. strcon(txt300,'''FIT2''',6,
     >                                       IS)) then
            read(lunR,*,end=13) IV
            do ii = 1, iv
              read(lunR,fmt='(a)',end=13) txt300
            enddo
            read(lunR,*,end=13) IC
            do ii = 1, ic
              read(lunR,fmt='(a)',end=13) txt300
            enddo

          elseif(strcon(txt300,'''END''',5,
     >                                       IS)) then
            goto 11

          else            
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))

          endif

        goto 1

 11     continue
              txt300 = '''MARKER''   #End'
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              txt300 = '''REBELOTE'''
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              txt300 = '99  0.2  99'
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              txt300 = '''END'''
              write(lunW,*) txt300(debstr(txt300):finstr(txt300)) 

 13   continue
      write(*,*) ' '
      write(*,*) ' End of zgoubi_spinN0FIT-In.dat input file has'
     >,' been reached, file  zgoubi_searchCO-In.dat  completed.'
      write(*,*) ' ------------'
      write(*,*) ' '
      close(lunR)
      close(lunW)

C Get closed orbits
      if (idluni(lunR)) then
        open(unit=lunR,file='searchCO.In',status='old',err=26)
      endif
      read(lunR,*,err=26,end=26) kaseV
      read(lunR,*,err=26,end=26) precX, precXp 
      close(lunR)
      goto 27
 26   continue
      kaseV = 2
      precX = .001d0 
      precXp = .01d0 
 27   continue
      cmmnd = '~/zgoubi/struct/tools/searchCO/searchCO_short'
      write(*,*) '---------------------------------------'
      write(*,*) cmmnd
      call system(cmmnd)

C Get spin N0
C Now build zgoubi.dat including SPNTRK and FIT, from zgoubi_searchCO_short-Out.dat
      if (idluni(lunR)) then
        open(unit=lunR,file='zgoubi_searchCO_short-Out.dat')
        rewind(lunR)
      endif
      if (idluni(lunW)) then
        open(unit=lunW,file='zgoubi_spinN0FIT-Out.dat')
        rewind(lunW)
      endif

C Read in zgoubi_searchCO_short-Out.dat
      read(lunR,fmt='(a)') txt300       ! title
      write(lunW,fmt='(a)') 'Data generated by  spinN0FIT '
      read(lunR,fmt='(a)') txt300     ! (MC)OBJET
      nlmnt = 1
      write(lunW,*) '''OBJET'''
      read(lunR,fmt='(a)') txt300     ! BORO
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))
      read(lunR,fmt='(a)') txt300     ! KOBJ=2
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))
      read(lunR,fmt='(a)') txt300     ! 1 1 
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))
      read(lunR,fmt='(a)') txt300     ! X,T,Y,P,...
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))
      read(lunR,fmt='(a)') txt300     ! 1
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))
      nlmnt = nlmnt + 1
C--------------------------------------------------
C Place PARTICUL and SPNTRK
      nlmnt = nlmnt + 1
      txt300 = '''PARTICUL'''
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      write(lunW,*) am, q, G, '  0. 0. '
      nlmnt = nlmnt + 1
      txt300 = '''SPNTRK'''
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      txt300 = ' 4.1 '
      write(lunW,*) txt300(debstr(txt300):finstr(txt300)) 
      txt300 = ' 0. 0. 1. '
      write(lunW,*) txt300(debstr(txt300):finstr(txt300)) 

C Complete zgoubi_spinN0FIT-Out.dat from content of zgoubi_searchCO_short-Out.dat
 30   continue
          read(lunR,fmt='(a)',end=13) txt300
          txt300 = txt300(debstr(txt300):132)

          if(strcon(txt300,'''FAISCEAU''',10,
     >                                           IS)) then 

          elseif(strcon(txt300,'''PARTICUL''',10,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''SPNTRK''',8,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300
            if(txt300(debstr(txt300):debstr(txt300)) .eq. '''') then
              nlmnt = nlmnt + 1
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            endif          

          elseif(strcon(txt300,'''PICKUPS''',9,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''SPNSTORE''',10,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''FAISTORE''',10,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''FAISCNL''',9,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''SPNPRNL''',9,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''REBELOTE''',10,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''MARKER''',8,
     >                                        IS)) then 
            txt300c = txt300(IS+8:132-8)
            txt300c = txt300c(debstr(txt300c):debstr(txt300c)+6)
            if(txt300c.eq.'#Start') then
            elseif(txt300c.eq.'#End') then
            else              
              nlmnt = nlmnt + 1
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            endif

          elseif(strcon(txt300,'''TWISS''',7,
     >                                         IS)) then
            read(lunR,fmt='(a)',end=13) txt300

          elseif(strcon(txt300,'''FIT''',5,
     >                                       IS)
     >      .or. strcon(txt300,'''FIT2''',6,
     >                                       IS)) then
            read(lunR,*,end=13) IV
            do ii = 1, iv
              read(lunR,fmt='(a)',end=13) txt300
            enddo
            read(lunR,*,end=13) IC
            do ii = 1, ic
              read(lunR,fmt='(a)',end=13) txt300
            enddo

          elseif(strcon(txt300,'''END''',5,
     >                                       IS)) then
            txt300 = '''SPNPRT'''
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            txt300 = '''FIT'''
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            txt300 = '    3'
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            txt300 = '    3  10  0  [-1.00001,1.00001]'
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            txt300 = '    3  11  0  [-1.00001,1.00001]'
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            txt300 = '    3  12  0  [-1.00001,1.00001]'
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            txt300 = '    4   1.e-8'
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              write(txt300,fmt='(a,i5,a)') 
     >           '  10    1 4 ',nlmnt,' 1. 1. 0  ' 
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              write(txt300,fmt='(a,i5,a)') 
     >           '  10.1  1 1 ',nlmnt,' 0. 1. 0   '
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              write(txt300,fmt='(a,i5,a)') 
     >           '  10.1  1 2 ',nlmnt,' 0. 1. 0   '
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              write(txt300,fmt='(a,i5,a)') 
     >           '  10.1  1 3 ',nlmnt,' 0. 1. 0   '
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))

              write(lunW,*) '''END'''

            goto 33

          else            
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              txt300 = txt300(debstr(txt300):finstr(txt300))
              if(txt300(1:1) .eq. '''') nlmnt = nlmnt + 1

          endif

        goto 30

 33     continue
      write(*,*) ' '
      write(*,*) ' End of zgoubi_searchCO_short-Out.dat input file has'
     >,' been reached  =>  file  zgoubi_spinN0FIT-Out.dat completed.'
      write(*,*) ' ------------'
      write(*,*) ' '
      close(lunR)
      close(lunW)

      cmmnd = 'cp -f zgoubi_spinN0FIT-Out.dat zgoubi.dat'
      write(*,*) '---------------------------------------'
      write(*,*) cmmnd
      call system(cmmnd)
      cmmnd = '~/zgoubi/SVN/current/zgoubi/zgoubi'
      write(*,*) '---------------------------------------'
      write(*,*) cmmnd
      call system(cmmnd)
      cmmnd = 'cp -f zgoubi.res zgoubi_spinN0FIT-Out.res'
      write(*,*) '---------------------------------------'
      write(*,*) cmmnd
      call system(cmmnd)

      write(*,*) ' '
      write(*,*) ' spinN0FIT job completed. '
      write(*,*) ' Results are available in  zgoubi_spinN0FIT-Out.res.'
      write(*,*) ' One way to check that spin N0 was found : '
     >,' look for SPNPRT at end of '
     >,' zgoubi_spinN0FIT-Out.res, there, make sure initial SX,SY,SZ'
     >,'=final SX,SY,SZ'
      write(*,*) ' '
      stop

 95   write(*,*) 'Please supply zgoubi_spinN0FIT-In.dat '
      write(*,*) '      - a copy of zgoubi.dat should do...'
      stop

 96   write(*,*) 'Please supply searchCO.In '
      stop

 999  continue
      write(*,*) ' '
      write(*,*) 'Provide spinN0FIT.In with particle data, e.g. :'
      write(*,*) '2808.39148  3.204352974e-19   -4.18415382 '
      write(*,*) '938.2720 1.602176487E-19 1.7928474 '
      write(*,*) ' '

      end
      FUNCTION STRCON(STR,STRIN,NCHAR,
     >                                IS)
      implicit double precision (a-h,o-z)
      LOGICAL STRCON
      CHARACTER STR*(*), STRIN*(*)
C     ------------------------------------------------------------------------
C     .TRUE. if the string STR contains the string STRIN with NCHAR characters
C     at least once.
C     IS = position of first occurence of STRIN in STR
C     ------------------------------------------------------------------------

      INTEGER DEBSTR,FINSTR

      II = 0
      DO 1 I = DEBSTR(STR), FINSTR(STR)
        II = II+1
        IF( STR(I:I+NCHAR-1) .EQ. STRIN ) THEN
          IS = II
          STRCON = .TRUE.
          RETURN
        ENDIF
 1    CONTINUE
      STRCON = .FALSE.
      RETURN
      END
      FUNCTION DEBSTR(STR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DEBSTR
      CHARACTER * (*) STR
C     -----------------------------------
C     Renvoie dans DEBSTR le rang du
C     premier caractere non-blanc de STR.
C     -----------------------------------
      DEBSTR=0
      LENGTH=LEN(STR)+1
1     CONTINUE
         DEBSTR=DEBSTR+1
         IF(DEBSTR.GE. LENGTH) RETURN
         IF (STR(DEBSTR:DEBSTR).EQ. ' ') GOTO 1
      RETURN
      END
      FUNCTION FINSTR(STRING)
      implicit double precision (a-h,o-z)
      INTEGER FINSTR
      CHARACTER * (*) STRING
C     --------------------------------------
C     RENVOIE DANS FINSTR LE RANG DU
C     DERNIER CHARACTER NON BLANC DE STRING,
C     OU BIEN 0 SI STRING EST VIDE ou BLANC.
C     --------------------------------------

      FINSTR=LEN(STRING)+1
1     CONTINUE
        FINSTR=FINSTR-1
        IF(FINSTR .EQ. 0) RETURN
        IF (STRING(FINSTR:FINSTR) .EQ. ' ') GOTO 1

      RETURN
      END
      FUNCTION IDLUNI(LN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL IDLUNI

      LOGICAL OPN

      I = 20
 1    CONTINUE
        INQUIRE(UNIT=I,ERR=99,IOSTAT=IOS,OPENED=OPN)
        I = I+1
        IF(I .EQ. 100) GOTO 99
        IF(OPN) GOTO 1
        IF(IOS .GT. 0) GOTO 1
      
      LN = I-1
      IDLUNI = .TRUE.
      RETURN

 99   CONTINUE
      LN = 0
      IDLUNI = .FALSE.
      RETURN
      END
