---
sudo: required
language: generic
services:
  - docker
env:
  global:
    - DOCKER_IMG="radiasoft/beamsim-part1"
    - BUILD_DIR="cmake-build"

before_install:
  - pwd
  - ls -l
  - ls -ld .
  - sudo chown -R 1000:1000 .
  - docker pull "${DOCKER_IMG}"

script:
  - bash travis.sh "${DOCKER_IMG}"

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
