---
sudo: required
language: generic
services:
  - docker
env:
  global:
    - DOCKER_IMG="radiasoft/beamsim"
    - BUILD_DIR="cmake-build"

before_install:
  - pwd
  - ls -l
  - ls -ld .
  - sudo chown -R 1000:1000 .
  - docker pull "${DOCKER_IMG}"

script:
  - bash travis.sh "${DOCKER_IMG}"

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
  slack:
    secure: si6EpocNDBsyVm3O0AVgKkPmMtgNwub+Oyo5ermYJYGqhVVprDeq8xbRBGs/8EEzlWiiUnp0b2y8fzuMUTywshwG6S7AM/LziK+kFJ1HlzSk2IwEfK67h0MthtHIy9+EGn2P15cqTRGme8A4fRsViloM7mc8VFUz9X/JkhM63adLVwAQVNzsSTsxMy3IaXURdTORIo/21xxtOr5jWNX97eMnbk7+jOYhiFR4gvdVZqByoWisb4uZcCGfSrkfc7aM2uoQzZE94YOrceenhg46jZH7eTOObRGatvISiUOwz1+y/NCP4XxrkHMZAKDNWYBJ7ONob9jorMKAzgxRYJ1D4I0TwEt6owFWKcS9K2Y8NknuPUM490rOhzDhVDVIKg/R2K+y7juwis0gOP64mpSiU8FdF3vz0WsUd40yu19rLCa0MeUAiEoQfFpf7Sc4sT+JZUZD8T0bUOi5lWYc83RfYwNMfwgHee5yq5qe0twzeg/vLzUDeNRIfy+Ct3JuWAhxGMFwNDk+CTbAjephzn8Z7lQpFRigKWp8AmY530jU6isQC6u/ntbt57zwzrnp4HplVRIScqSxOrVyl1TU7fCv6rWlJcuh7Yo/GmYXQHa3f3qRQ5PVVRkZ9nVWCfd84Yld53/ibwFUvucCe3vM7Y+7jXtZSZRUSnC/4ECXLKM/XAQ=
