---
sudo: required
language: generic
services:
  - docker
env:
  global:
    - DOCKER_IMG="radiasoft/beamsim-part1"

before_install:
  - docker pull "${DOCKER_IMG}"
  - pwd

script:
  - bash travis.sh "${DOCKER_IMG}"

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
