Data generated by searchCO
 'OBJET'                                                                                                      1
7.20517829566983d3
1
10    1  1 1 1 1
0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00   0.00  0.000000E+00
-2.47911252E+00   0.00000000E+00   0.00000000E+00   0.00000000E+00   0.00  1.00000000E+00
 
 
 'PARTICUL'                                                                                                   2
9.3827203E+02 1.602176487E-19 1.7928474 0 0
 'SPNTRK'                                                                                                     3
5
0.000000E+00   1.570796E+00 ! TO=0, PO=90 deg (initial \vec S 0 on Z axis)
1.700000E-02   1.700000E-03 ! A and dA, installation to be completed in spn.f
123456
 
 'SPNPRT'                                                                                                     4
 'FAISCEAU'                                                                                                   5
 
 'DRIFT' DRIF   CSNK                                                                                          6
-20.
 'TOSCA'                                                                                                      7
0  20
9.81791462E+00  1.00000000E+00  1.00000000E+00  1.00000000E+00
HEADER_9
321 29 29  15.2 1.10  0.3153769053
b_ags-full-coilv5-x06-rerun2-x071-integral-x5y5z10mm.table
b_ags-full-sold3-only-nodal-x5y5z10mm-wasactually-integral.table
0 0 0 0
2
2   0.00000000E+00  0.00000000E+00  0.00000000E+00
2  0.  .00  0.  0.
 'DRIFT' DRIF   CSNK                                                                                          8
-20.
 
 'REBELOTE'   ! Useless... just to check emdding in FIT is ok                                                 9
9  0.1  0
 
 'FAISCEAU'                                                                                                  10
 'SPNPRT'                                                                                                    11
 
 'FIT'                                                                                                       12
2
1 40 0  [-5,5]       ! Vary Y(prtcl 1)
7 10 0  .2           ! Vary snake field
3   1e-10  30
7.3  1 2 7    0.         1. 0   ! prtcl i=1, coord j=2=Y  to satisfy  max_Y+min_Y =0, across lmnt ir=6.
10.4  1 3 #End 0.8660254 .2 0   ! <S_Z>_particles ->  \vec S at 30 degrees from Z axis.
10    1 4 #End 1.        .2 0   ! |S_F| = 1.
 
 'FAISCEAU'                                                                                                  13
 'SPNPRT'                                                                                                    14
 
 'END'                                                                                                       15

************************************************************************************************************************************
      1  Keyword, label(s) :  OBJET                                                 

                          MAGNETIC  RIGIDITY =       7205.178 kG*cm

                                         TRAJECTOIRY SETTING UP

                              OBJET  (1)  BUILT  UP  FROM      10 POINTS 



                                 D         Y(cm)       T(mrd)      Z(cm)       P(mrd)      X(cm)

                     NUMBER         1          10           1           1           1           0


                    SAMPLING      0.0000      0.00        0.00        0.00        0.00        0.00


************************************************************************************************************************************
      2  Keyword, label(s) :  PARTICUL                                              


     Particle  properties :
      
                     Mass          =    938.272        MeV/c2
                     Charge        =   1.602176E-19    C     
                     G  factor     =    1.79285              

              Reference  data :
                    mag. rigidity (kG.cm)   :   7205.1783      =p/q, such that dev.=B*L/rigidity
                    mass (MeV/c2)           :   938.27203    
                    momentum (MeV/c)        :   2160.0581    
                    energy, total (MeV)     :   2355.0383    
                    energy, kinetic (MeV)   :   1416.7663    
                    beta = v/c              :  0.9172072069    
                    gamma                   :   2.509973905    
                    beta*gamma              :   2.302166155    
                    G*gamma                 :   4.500000190    
                    electric rigidity (MeV) :   1981.220867      =T[eV]*(gamma+1)/gamma, such that dev.=E*L/rigidity
  
 I, AMQ(1,I), AMQ(2,I)/QE, P/Pref, v/c, time, s :
  
     1   9.38272030E+02  1.00000000E+00  1.00000000E+00  9.17207207E-01  0.00000000E+00  0.00000000E+00
     2   9.38272030E+02  1.00000000E+00  1.00000000E+00  9.17207207E-01  0.00000000E+00  0.00000000E+00
     3   9.38272030E+02  1.00000000E+00  1.00000000E+00  9.17207207E-01  0.00000000E+00  0.00000000E+00
     4   9.38272030E+02  1.00000000E+00  1.00000000E+00  9.17207207E-01  0.00000000E+00  0.00000000E+00
     5   9.38272030E+02  1.00000000E+00  1.00000000E+00  9.17207207E-01  0.00000000E+00  0.00000000E+00
     6   9.38272030E+02  1.00000000E+00  1.00000000E+00  9.17207207E-01  0.00000000E+00  0.00000000E+00
     7   9.38272030E+02  1.00000000E+00  1.00000000E+00  9.17207207E-01  0.00000000E+00  0.00000000E+00
     8   9.38272030E+02  1.00000000E+00  1.00000000E+00  9.17207207E-01  0.00000000E+00  0.00000000E+00
     9   9.38272030E+02  1.00000000E+00  1.00000000E+00  9.17207207E-01  0.00000000E+00  0.00000000E+00
    10   9.38272030E+02  1.00000000E+00  1.00000000E+00  9.17207207E-01  0.00000000E+00  0.00000000E+00

************************************************************************************************************************************
      3  Keyword, label(s) :  SPNTRK                                                


                SPIN  TRACKING  REQUESTED  

                          PARTICLE  MASS          =    938.2720     MeV/c2
                          GYROMAGNETIC  FACTOR  G =    1.792847    

                          INITIAL SPIN CONDITIONS TYPE  5 :
          TO, PO, A, dA :   0.00000E+00  1.57080E+00  1.70000E-02  1.70000E-03

               WARNING :  INSTALLATION OF KSO=5 NEEDS BE COMPLETED !



                          PARAMETRES  DYNAMIQUES  DE  REFERENCE :
                               BORO   =      7205.178 KG*CM
                               BETA   =    0.917207
                               GAMMA*G =   4.500000


                          POLARISATION  INITIALE  MOYENNE  DU  FAISCEAU  DE       10  PARTICULES :
                               <SX> =     0.000000
                               <SY> =     0.000000
                               <SZ> =     1.000000
                               <S>  =     1.000000

************************************************************************************************************************************
      4  Keyword, label(s) :  SPNPRT                                                



                         Momentum  group  #1 ; average  over 10 particles at this pass : 

                   INITIAL                                           FINAL

      <SX>       <SY>       <SZ>       <|S|>            <SX>       <SY>       <SZ>      <|S|>    <G.gma>    <(SI,SF)>  sigma_(SI,SF)
                                                                                                               (deg)       (deg)
   0.000000   0.000000   1.000000   1.000000         0.000000   0.000000   1.000000   1.000000   4.500000   0.000000   0.000000


                Spin  components  of  each  of  the     10  particles,  and  rotation  angle :

                   INITIAL                                           FINAL

           SX        SY        SZ        |S|         SX        SY        SZ        |S|       GAMMA   (Si,Sf)   (Z,Sf_X)  (Z,Sf)
                                                                                                      (deg.)    (deg.)    (deg.)
                                                                                           (Sf_X : projection of Sf on YZ plane)

 O  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    1
 A  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    2
 B  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    3
 C  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    4
 D  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    5
 E  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    6
 F  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    7
 G  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    8
 H  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    9
 I  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000   10



                Min/Max  components  of  each  of  the     10  particles :

  SX_mi       SX_ma       SY_mi       SY_ma       SZ_mi       SZ_ma       |S|_mi      |S|_ma      p/p_0        GAMMA          I  IEX

 -3.2679E-07 -3.2679E-07  4.6140E-11  4.6140E-11  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      1   1
 -2.8125E-07 -2.8125E-07  1.6641E-07  1.6641E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      2   1
  2.6274E-07  2.6274E-07 -1.9433E-07 -1.9433E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      3   1
 -2.5390E-07 -2.5390E-07 -2.0575E-07 -2.0575E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      4   1
 -3.2019E-07 -3.2019E-07 -6.5353E-08 -6.5353E-08  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      5   1
 -1.2089E-07 -1.2089E-07  3.0361E-07  3.0361E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      6   1
  3.2535E-07  3.2535E-07 -3.0705E-08 -3.0705E-08  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      7   1
  2.6196E-07  2.6196E-07  1.9538E-07  1.9538E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      8   1
  2.6471E-08  2.6471E-08  3.2572E-07  3.2572E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      9   1
  1.3317E-08  1.3317E-08 -3.2652E-07 -3.2652E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00     10   1

************************************************************************************************************************************
      5  Keyword, label(s) :  FAISCEAU                                              

0                                             TRACE DU FAISCEAU
                                           (follows element #      4)
                                                 10 TRAJECTOIRES

                                   OBJET                                                  FAISCEAU

          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)

O  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     1
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
A  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     2
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
B  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     3
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
C  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     4
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
D  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     5
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
E  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     6
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
F  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     7
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
G  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     8
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
H  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     9
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
I  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00    10
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    


------
  Characteristics of concentration ellipse (Surface, ALP, BET, <X>, <XP>, #prtcls, #prtcls inside ellips, ratio, space, pass#) : 

   0.0000E+00   0.0000E+00   1.0000E+00  -2.479113E-02   0.000000E+00       10        0    0.000      (Y,T)         1
   0.0000E+00   0.0000E+00   1.0000E+00   0.000000E+00   0.000000E+00       10       10    1.000      (Z,P)         1
   0.0000E+00   0.0000E+00   1.0000E+00   0.000000E+00   1.416766E+03       10        0    0.000      (t,K)         1

(Y,T)  space (units : (cm,rd)   ) :  
      sigma_Y = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_T = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(Z,P)  space (units : (cm,rd)   ) :  
      sigma_Z = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_P = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(t,K)  space (units : (mu_s,MeV)) :  
      sigma_t = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_K = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00


  Beam  sigma  matrix : 

   1.203706E-35   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00

      sqrt(det_Y), sqrt(det_Z) :     0.000000E+00    0.000000E+00    (Note :  sqrt(determinant) = ellipse surface / pi)

************************************************************************************************************************************
      6  Keyword, label(s) :  DRIFT       DRIF                  CSNK                


                              Drift,  length =   -20.00000  cm

TRAJ #1 IEX,D,Y,T,Z,P,S,time :  1  0.000000E+00 -2.479113E+00  0.000000E+00  0.000000E+00  0.000000E+00  -2.0000000E+01  -7.27347E-04
TRAJ #1 SX, SY, SZ, |S| :  1   -3.267949E-07   4.613989E-11   1.000000E+00   1.000000E+00

 Cumulative length of optical axis =  -0.200000000     m   ;  Time  (for reference rigidity & particle) =  -7.273473E-10 s 

************************************************************************************************************************************
      7  Keyword, label(s) :  TOSCA                                                 


                OPEN FILE zgoubi.plt                                                                      
                FOR PRINTING TRAJECTORIES


     Status of MOD.MOD2 is 15.2 ; NDIM = 3 ; number of field data files used is   2.
     Field map set stored in field array HC(IMAP = 1)
     3-D map. MOD=15.   Will sum up  2  field maps, with field coefficient values : 
                 1.100000E+00  3.153769E-01

     ZroBXY OPTION :  absent from map title. BX and BY values in Z=0 plane left as read.

           New field map(s) opened, cartesian mesh (MOD.le.19) ; 
           name(s) of map data file(s) : 

          b_ags-full-coilv5-x06-rerun2-x071-integral-x5y5z10mm.table
          b_ags-full-sold3-only-nodal-x5y5z10mm-wasactually-integral.table

   ----
   Map file number    1 ( of 2) :

     b_ags-full-coilv5-x06-rerun2-x071-integral-x5y5z10mm.table map, FORMAT type : regular.  Field multiplication factor :  1.10000000E+00

 HEADER  (9 lines) : 
               29          29         321           1                                                                        
      1 X [LENGU]                                                                                                            
      2 Y [LENGU]                                                                                                            
      3 Z [LENGU]                                                                                                            
      4 BX [1]                                                                                                               
      5 BY [1]                                                                                                               
      6 BZ [1]                                                                                                               
      7 BMOD [1]                                                                                                             
      0                                                                                                                      
R_min (cm), DR (cm), DTTA (deg), DZ (cm) :    0.00000000E+00   0.00000000E+00   0.00000000E+00   0.00000000E+00

  Sbr fmapw/fmapr3 : completed job of reading map.

   ----
   Map file number    2 ( of 2) :

     b_ags-full-sold3-only-nodal-x5y5z10mm-wasactually-integral.table map, FORMAT type : regular.  Field multiplication factor :  3.15376905E-01

 HEADER  (9 lines) : 
               29          29         321           1                                                                        
      1 X [LENGU]                                                                                                            
      2 Y [LENGU]                                                                                                            
      3 Z [LENGU]                                                                                                            
      4 BX [1]                                                                                                               
      5 BY [1]                                                                                                               
      6 BZ [1]                                                                                                               
      7 BMOD [1]                                                                                                             
      0                                                                                                                      
R_min (cm), DR (cm), DTTA (deg), DZ (cm) :    0.00000000E+00   0.00000000E+00   0.00000000E+00   5.00000000E-01

  Sbr fmapw/fmapr3 : completed job of reading map.
     Field from  2 map(s) is combined (summed up) with linear combination coefficient(s) a(i=1-4), respectively) : 
            1.100000E+00  3.153769E-01

     Min/max fields found in map (series) read   :  -4.821803E-02  /   7.427127E-02
       @  X,  Y, Z :   41.0      -7.00       6.00                  /   0.00       6.50       6.50    
     Given normalisation coeffs on field, x, y, z :   9.817915E+00   1.000000E+00   1.000000E+00   1.000000E+00
     this yields min/max normalised fields (kG) : -4.734005E-01                      7.291890E-01
       @  X (cm),  Y (cm), Z (cm) :   41.0      -7.00       6.00   /   0.00       6.50       6.50    

     Length of element,  XL =  3.200000E+02 cm 
                                               from  XI =  -1.600000E+02 cm 
                                               to    XF =   1.600000E+02 cm 

     Nbr of nodes in X = 321;  nbr of nodes in Y =   29
     X-size of mesh =  1.000000E+00 cm ; Y-size =  5.000000E-01 cm
     nber of mesh nodes in Z =   29 ; Step in Z =  0.500000E+00 cm

                     OPTION  DE  CALCUL  :  GRILLE  3-D  A  3*3*3  POINTS , INTERPOLATION  A  L'ORDRE  2

                    Integration step :   2.000     cm

  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            1
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            2
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            3
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            4
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            5
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            6
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            7
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            8
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            9
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000           10


                CONDITIONS  DE  MAXWELL  (     1610.  PAS )  :
                       DIV(B)        LAPLACIEN(B)     ROTATIONNEL(B)
                     7.6211E-15      -9.5846E-16        2.7712E-16
                                     -3.7057E-15       -1.6427E-14
                                     -2.8156E-15        2.6559E-14
                       LAPLACIEN SCALAIRE =   0.000    



     KPOS =  2.  Element  is  mis-aligned  wrt.  the  optical  axis.
          X =   0.000     CM   Y =   0.000     cm,  tilt  angle =   0.00000     RAD


 Cumulative length of optical axis =    3.00000000     m ;  Time  (for ref. rigidity & particle) =   1.091021E-08 s 

************************************************************************************************************************************
      8  Keyword, label(s) :  DRIFT       DRIF                  CSNK                


                              Drift,  length =   -20.00000  cm

TRAJ #1 IEX,D,Y,T,Z,P,S,time :  1  0.000000E+00 -2.343751E+00  1.029929E+00 -1.980827E-01 -4.406253E-01   2.8069032E+02   1.02080E-02
TRAJ #1 SX, SY, SZ, |S| :  1   -8.439005E-03   4.969854E-01   8.677178E-01   1.000000E+00

 Cumulative length of optical axis =    2.80000000     m   ;  Time  (for reference rigidity & particle) =   1.018286E-08 s 

************************************************************************************************************************************
      9  Keyword, label(s) :  REBELOTE                                              


                                -----  REBELOTE  -----

     End of pass #        1 through the optical structure 

                     Total of         10 particles have been launched

     Multiple pass, 
          from element #     1 : OBJET     /label1=                    /label2=                    
                             to  REBELOTE  /label1=                    /label2=                    
     ending at pass #      10 at element #     9 : REBELOTE  /label1=                    /label2=                    


     WRITE statements to zgoubi.res are inhibeted from now on.

************************************************************************************************************************************

                                -----  REBELOTE  -----

     End of pass #        2 through the optical structure 

                     Total of         20 particles have been launched

                                -----  REBELOTE  -----

     End of pass #        3 through the optical structure 

                     Total of         30 particles have been launched

                                -----  REBELOTE  -----

     End of pass #        4 through the optical structure 

                     Total of         40 particles have been launched

                                -----  REBELOTE  -----

     End of pass #        5 through the optical structure 

                     Total of         50 particles have been launched

                                -----  REBELOTE  -----

     End of pass #        6 through the optical structure 

                     Total of         60 particles have been launched

                                -----  REBELOTE  -----

     End of pass #        7 through the optical structure 

                     Total of         70 particles have been launched

                                -----  REBELOTE  -----

     End of pass #        8 through the optical structure 

                     Total of         80 particles have been launched

                                -----  REBELOTE  -----

     End of pass #        9 through the optical structure 

                     Total of         90 particles have been launched


      Next  pass  is  #    10 and  last  pass  through  the  optical  structure


************************************************************************************************************************************
      1  Keyword, label(s) :  OBJET                                                 

                          MAGNETIC  RIGIDITY =       7205.178 kG*cm

                                         TRAJECTOIRY SETTING UP

                              OBJET  (1)  BUILT  UP  FROM      10 POINTS 



                                 D         Y(cm)       T(mrd)      Z(cm)       P(mrd)      X(cm)

                     NUMBER         1          10           1           1           1           0


                    SAMPLING      0.0000      0.00        0.00        0.00        0.00        0.00


************************************************************************************************************************************
      2  Keyword, label(s) :  PARTICUL                                              


************************************************************************************************************************************
      3  Keyword, label(s) :  SPNTRK                                                


                SPIN  TRACKING  REQUESTED  

                          PARTICLE  MASS          =    938.2720     MeV/c2
                          GYROMAGNETIC  FACTOR  G =    1.792847    

                          INITIAL SPIN CONDITIONS TYPE  5 :
          TO, PO, A, dA :   0.00000E+00  1.57080E+00  1.70000E-02  1.70000E-03

               WARNING :  INSTALLATION OF KSO=5 NEEDS BE COMPLETED !



                          PARAMETRES  DYNAMIQUES  DE  REFERENCE :
                               BORO   =      7205.178 KG*CM
                               BETA   =    0.917207
                               GAMMA*G =   4.500000


                          POLARISATION  INITIALE  MOYENNE  DU  FAISCEAU  DE       10  PARTICULES :
                               <SX> =     0.000000
                               <SY> =     0.000000
                               <SZ> =     1.000000
                               <S>  =     1.000000

************************************************************************************************************************************
      4  Keyword, label(s) :  SPNPRT                                                



                         Momentum  group  #1 ; average  over 10 particles at this pass : 

                   INITIAL                                           FINAL

      <SX>       <SY>       <SZ>       <|S|>            <SX>       <SY>       <SZ>      <|S|>    <G.gma>    <(SI,SF)>  sigma_(SI,SF)
                                                                                                               (deg)       (deg)
   0.000000   0.000000   1.000000   1.000000         0.000000   0.000000   1.000000   1.000000   4.500000   0.000000   0.000000


                Spin  components  of  each  of  the     10  particles,  and  rotation  angle :

                   INITIAL                                           FINAL

           SX        SY        SZ        |S|         SX        SY        SZ        |S|       GAMMA   (Si,Sf)   (Z,Sf_X)  (Z,Sf)
                                                                                                      (deg.)    (deg.)    (deg.)
                                                                                           (Sf_X : projection of Sf on YZ plane)

 O  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    1
 A  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    2
 B  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    3
 C  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    4
 D  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    5
 E  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    6
 F  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    7
 G  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    8
 H  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    9
 I  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000   10



                Min/Max  components  of  each  of  the     10  particles :

  SX_mi       SX_ma       SY_mi       SY_ma       SZ_mi       SZ_ma       |S|_mi      |S|_ma      p/p_0        GAMMA          I  IEX

 -3.2679E-07  3.2668E-07 -3.1147E-07  3.1259E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      1   1
 -3.2625E-07  3.1997E-07 -1.8035E-07  2.9686E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      2   1
 -2.6378E-07  2.8734E-07 -3.0985E-07  3.0500E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      3   1
 -2.5390E-07  3.2537E-07 -3.0417E-07  3.2376E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      4   1
 -3.2019E-07  3.2642E-07 -3.2606E-07  3.0947E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      5   1
 -3.1730E-07  3.2591E-07 -3.2343E-07  3.2409E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      6   1
 -2.9422E-07  3.2535E-07 -3.0319E-07  2.8099E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      7   1
 -3.2664E-07  3.1423E-07 -2.5441E-07  3.0523E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      8   1
 -2.7469E-07  3.0517E-07 -3.2315E-07  3.2572E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      9   1
 -3.2641E-07  2.1985E-07 -3.2652E-07  3.2663E-07  1.0000E+00  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00     10   1

************************************************************************************************************************************
      5  Keyword, label(s) :  FAISCEAU                                              

0                                             TRACE DU FAISCEAU
                                           (follows element #      4)
                                                 10 TRAJECTOIRES

                                   OBJET                                                  FAISCEAU

          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)

O  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     1
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
A  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     2
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
B  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     3
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
C  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     4
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
D  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     5
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
E  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     6
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
F  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     7
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
G  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     8
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
H  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00     9
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
I  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.479    0.000    0.000    0.000   0.000000E+00    10
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    


------
  Characteristics of concentration ellipse (Surface, ALP, BET, <X>, <XP>, #prtcls, #prtcls inside ellips, ratio, space, pass#) : 

   0.0000E+00   0.0000E+00   1.0000E+00  -2.479113E-02   0.000000E+00       10        0    0.000      (Y,T)        10
   0.0000E+00   0.0000E+00   1.0000E+00   0.000000E+00   0.000000E+00       10       10    1.000      (Z,P)        10
   0.0000E+00   0.0000E+00   1.0000E+00   0.000000E+00   1.416766E+03       10        0    0.000      (t,K)        10

(Y,T)  space (units : (cm,rd)   ) :  
      sigma_Y = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_T = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(Z,P)  space (units : (cm,rd)   ) :  
      sigma_Z = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_P = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(t,K)  space (units : (mu_s,MeV)) :  
      sigma_t = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_K = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00


  Beam  sigma  matrix : 

   1.203706E-35   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00

      sqrt(det_Y), sqrt(det_Z) :     0.000000E+00    0.000000E+00    (Note :  sqrt(determinant) = ellipse surface / pi)

************************************************************************************************************************************
      6  Keyword, label(s) :  DRIFT       DRIF                  CSNK                


                              Drift,  length =   -20.00000  cm

TRAJ #1 IEX,D,Y,T,Z,P,S,time :  1  0.000000E+00 -2.479113E+00  0.000000E+00  0.000000E+00  0.000000E+00  -2.0000000E+01  -7.27347E-04
TRAJ #1 SX, SY, SZ, |S| :  1   -9.891137E-08  -3.114666E-07   1.000000E+00   1.000000E+00

 Cumulative length of optical axis =  -0.200000000     m   ;  Time  (for reference rigidity & particle) =   9.091841E-08 s 

************************************************************************************************************************************
      7  Keyword, label(s) :  TOSCA                                                 


     zgoubi.plt                                                                      
      already open...

     Status of MOD.MOD2 is 15.2 ; NDIM = 3 ; number of field data files used is   2.
     Field map set stored in field array HC(IMAP = 1)
     3-D map. MOD=15.   Will sum up  2  field maps, with field coefficient values : 
                 1.100000E+00  3.153769E-01

     ZroBXY OPTION :  absent from map title. BX and BY values in Z=0 plane left as read.

     No  map  file  opened :  was  already  stored.
     Skip  reading  field  map  file :           b_ags-full-coilv5-x06-rerun2-x071-integral-x5y5z10mm.table

     No  map  file  opened :  was  already  stored.
     Skip  reading  field  map  file :           b_ags-full-sold3-only-nodal-x5y5z10mm-wasactually-integral.table
     Restored mesh coordinates for field map #IMAP=   1,  name : b_ags-full-sold3-only-nodal-x5y5z10mm-wasactually-integral.table
     Field from  2 map(s) is combined (summed up) with linear combination coefficient(s) a(i=1-4), respectively) : 
            1.100000E+00  3.153769E-01

     Min/max fields found in map (series) read   :  -4.821803E-02  /   7.427127E-02
       @  X,  Y, Z :   41.0      -7.00       6.00                  /   0.00       6.50       6.50    
     Given normalisation coeffs on field, x, y, z :   9.817915E+00   1.000000E+00   1.000000E+00   1.000000E+00
     this yields min/max normalised fields (kG) : -4.734005E-01                      7.291890E-01
       @  X (cm),  Y (cm), Z (cm) :   41.0      -7.00       6.00   /   0.00       6.50       6.50    

     Length of element,  XL =  3.200000E+02 cm 
                                               from  XI =  -1.600000E+02 cm 
                                               to    XF =   1.600000E+02 cm 

     Nbr of nodes in X = 321;  nbr of nodes in Y =   29
     X-size of mesh =  1.000000E+00 cm ; Y-size =  5.000000E-01 cm
     nber of mesh nodes in Z =   29 ; Step in Z =  0.500000E+00 cm

                     OPTION  DE  CALCUL  :  GRILLE  3-D  A  3*3*3  POINTS , INTERPOLATION  A  L'ORDRE  2

                    Integration step :   2.000     cm

  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            1
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            2
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            3
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            4
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            5
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            6
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            7
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            8
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000            9
  A    1  1.0000    -2.479     0.000     0.000     0.000          160.000    -2.323     0.001    -0.207     0.000           10


                CONDITIONS  DE  MAXWELL  (     1610.  PAS )  :
                       DIV(B)        LAPLACIEN(B)     ROTATIONNEL(B)
                     7.6211E-15      -9.5846E-16        2.7712E-16
                                     -3.7057E-15       -1.6427E-14
                                     -2.8156E-15        2.6559E-14
                       LAPLACIEN SCALAIRE =   0.000    



     KPOS =  2.  Element  is  mis-aligned  wrt.  the  optical  axis.
          X =   0.000     CM   Y =   0.000     cm,  tilt  angle =   0.00000     RAD


 Cumulative length of optical axis =    3.00000000     m ;  Time  (for ref. rigidity & particle) =   1.025560E-07 s 

************************************************************************************************************************************
      8  Keyword, label(s) :  DRIFT       DRIF                  CSNK                


                              Drift,  length =   -20.00000  cm

TRAJ #1 IEX,D,Y,T,Z,P,S,time :  1  0.000000E+00 -2.343751E+00  1.029929E+00 -1.980827E-01 -4.406253E-01   2.8069032E+02   1.02080E-02
TRAJ #1 SX, SY, SZ, |S| :  1   -8.438766E-03   4.969852E-01   8.677180E-01   1.000000E+00

 Cumulative length of optical axis =    2.80000000     m   ;  Time  (for reference rigidity & particle) =   1.018286E-07 s 

************************************************************************************************************************************
      9  Keyword, label(s) :  REBELOTE                                              


                         ****  End  of  'REBELOTE'  procedure  ****

      There  has  been         10  passes  through  the  optical  structure 

                     Total of        100 particles have been launched

************************************************************************************************************************************
     10  Keyword, label(s) :  FAISCEAU                                              

0                                             TRACE DU FAISCEAU
                                           (follows element #      9)
                                                 10 TRAJECTOIRES

                                   OBJET                                                  FAISCEAU

          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)

O  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.344    1.030   -0.198   -0.441   2.806903E+02     1
               Time of flight (mus) :  1.02079674E-02 mass (MeV/c2) :   938.272    
A  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.344    1.030   -0.198   -0.441   2.806903E+02     2
               Time of flight (mus) :  1.02079674E-02 mass (MeV/c2) :   938.272    
B  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.344    1.030   -0.198   -0.441   2.806903E+02     3
               Time of flight (mus) :  1.02079674E-02 mass (MeV/c2) :   938.272    
C  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.344    1.030   -0.198   -0.441   2.806903E+02     4
               Time of flight (mus) :  1.02079674E-02 mass (MeV/c2) :   938.272    
D  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.344    1.030   -0.198   -0.441   2.806903E+02     5
               Time of flight (mus) :  1.02079674E-02 mass (MeV/c2) :   938.272    
E  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.344    1.030   -0.198   -0.441   2.806903E+02     6
               Time of flight (mus) :  1.02079674E-02 mass (MeV/c2) :   938.272    
F  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.344    1.030   -0.198   -0.441   2.806903E+02     7
               Time of flight (mus) :  1.02079674E-02 mass (MeV/c2) :   938.272    
G  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.344    1.030   -0.198   -0.441   2.806903E+02     8
               Time of flight (mus) :  1.02079674E-02 mass (MeV/c2) :   938.272    
H  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.344    1.030   -0.198   -0.441   2.806903E+02     9
               Time of flight (mus) :  1.02079674E-02 mass (MeV/c2) :   938.272    
I  1   1.0000    -2.479     0.000     0.000     0.000       0.0000    1.0000   -2.344    1.030   -0.198   -0.441   2.806903E+02    10
               Time of flight (mus) :  1.02079674E-02 mass (MeV/c2) :   938.272    


------
  Characteristics of concentration ellipse (Surface, ALP, BET, <X>, <XP>, #prtcls, #prtcls inside ellips, ratio, space, pass#) : 

   0.0000E+00   0.0000E+00   1.0000E+00  -2.343751E-02   1.029929E-03       10        0    0.000      (Y,T)        11
   0.0000E+00   0.0000E+00   1.0000E+00  -1.980827E-03  -4.406253E-04       10        0    0.000      (Z,P)        11
   0.0000E+00   0.0000E+00   1.0000E+00   1.020797E-02   1.416766E+03       10        0    0.000      (t,K)        11

(Y,T)  space (units : (cm,rd)   ) :  
      sigma_Y = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_T = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(Z,P)  space (units : (cm,rd)   ) :  
      sigma_Z = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_P = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(t,K)  space (units : (mu_s,MeV)) :  
      sigma_t = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_K = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00


  Beam  sigma  matrix : 

   1.203706E-35   0.000000E+00   0.000000E+00  -1.880791E-37
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
  -1.880791E-37   0.000000E+00   0.000000E+00   2.938736E-39

      sqrt(det_Y), sqrt(det_Z) :     0.000000E+00    0.000000E+00    (Note :  sqrt(determinant) = ellipse surface / pi)

************************************************************************************************************************************
     11  Keyword, label(s) :  SPNPRT                                                



                         Momentum  group  #1 ; average  over 10 particles at this pass : 

                   INITIAL                                           FINAL

      <SX>       <SY>       <SZ>       <|S|>            <SX>       <SY>       <SZ>      <|S|>    <G.gma>    <(SI,SF)>  sigma_(SI,SF)
                                                                                                               (deg)       (deg)
   0.000000   0.000000   1.000000   1.000000        -0.008439   0.496985   0.867718   1.000000   4.500000  29.805489   0.000000


                Spin  components  of  each  of  the     10  particles,  and  rotation  angle :

                   INITIAL                                           FINAL

           SX        SY        SZ        |S|         SX        SY        SZ        |S|       GAMMA   (Si,Sf)   (Z,Sf_X)  (Z,Sf)
                                                                                                      (deg.)    (deg.)    (deg.)
                                                                                           (Sf_X : projection of Sf on YZ plane)

 O  1  0.000000  0.000000  1.000000  1.000000    -0.008439  0.496985  0.867718  1.000000      2.5100   29.805   29.802   29.805    1
 A  1  0.000000  0.000000  1.000000  1.000000    -0.008438  0.496985  0.867718  1.000000      2.5100   29.805   29.802   29.805    2
 B  1  0.000000  0.000000  1.000000  1.000000    -0.008439  0.496985  0.867718  1.000000      2.5100   29.805   29.802   29.805    3
 C  1  0.000000  0.000000  1.000000  1.000000    -0.008439  0.496986  0.867718  1.000000      2.5100   29.805   29.802   29.806    4
 D  1  0.000000  0.000000  1.000000  1.000000    -0.008439  0.496986  0.867718  1.000000      2.5100   29.805   29.802   29.806    5
 E  1  0.000000  0.000000  1.000000  1.000000    -0.008439  0.496986  0.867718  1.000000      2.5100   29.805   29.802   29.806    6
 F  1  0.000000  0.000000  1.000000  1.000000    -0.008438  0.496986  0.867718  1.000000      2.5100   29.805   29.802   29.806    7
 G  1  0.000000  0.000000  1.000000  1.000000    -0.008439  0.496986  0.867718  1.000000      2.5100   29.805   29.802   29.805    8
 H  1  0.000000  0.000000  1.000000  1.000000    -0.008438  0.496985  0.867718  1.000000      2.5100   29.805   29.802   29.805    9
 I  1  0.000000  0.000000  1.000000  1.000000    -0.008438  0.496985  0.867718  1.000000      2.5100   29.805   29.802   29.805   10



                Min/Max  components  of  each  of  the     10  particles :

  SX_mi       SX_ma       SY_mi       SY_ma       SZ_mi       SZ_ma       |S|_mi      |S|_ma      p/p_0        GAMMA          I  IEX

 -8.4388E-03  3.2668E-07 -3.1147E-07  4.9699E-01  8.6772E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      1   1
 -8.4384E-03  3.1997E-07 -1.8035E-07  4.9699E-01  8.6772E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      2   1
 -8.4389E-03  2.8734E-07 -3.0985E-07  4.9699E-01  8.6772E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      3   1
 -8.4386E-03  3.2537E-07 -3.0417E-07  4.9699E-01  8.6772E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      4   1
 -8.4388E-03  3.2642E-07 -3.2606E-07  4.9699E-01  8.6772E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      5   1
 -8.4386E-03  3.2591E-07 -3.2343E-07  4.9699E-01  8.6772E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      6   1
 -8.4384E-03  3.2535E-07 -3.0319E-07  4.9699E-01  8.6772E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      7   1
 -8.4390E-03  3.1423E-07 -2.5441E-07  4.9699E-01  8.6772E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      8   1
 -8.4385E-03  3.0517E-07 -3.2315E-07  4.9699E-01  8.6772E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      9   1
 -8.4385E-03  2.1985E-07 -3.2652E-07  4.9699E-01  8.6772E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00     10   1

************************************************************************************************************************************
     12  Keyword, label(s) :  FIT                                                   

     FIT procedure launched. Method is 1

           variable #            1       IR =            1 ,   ok.
           variable #            1       IP =           40 ,   ok.
           variable #            2       IR =            7 ,   ok.
           variable #            2       IP =           10 ,   ok.
           constraint #            1       IR =            7 ,   ok.
           constraint #            2       IR =           11 ,   ok.
           constraint #            3       IR =           11 ,   ok.

                    FIT  variables  in  good  order,  FIT  will proceed. 

                    Final FIT status will NOT be saved. For so, use the 'save [FileName]' command

 STATUS OF VARIABLES  (Iteration #     0 /     30 max.)
  LMNT  VAR  PARAM   MINIMUM     INITIAL         FINAL         MAXIMUM     STEP     NAME       LBL1                 LBL2
     1    1     40   -5.00       -2.49       -2.490223631       5.00      1.524E-05 OBJET      -                    -                   
     7    2     10    7.85        9.85        9.852014702       11.8      5.986E-06 TOSCA      -                    -                   
 STATUS OF CONSTRAINTS (Target penalty =   1.0000E-10)
 TYPE  I   J  LMNT#       DESIRED           WEIGHT         REACHED         KI2       NAME       LBL1                 LBL2                 Parameter(s) 
   7   1   2     7      0.0000000E+00     1.0000E+00   -8.7606153E-06   2.7515E-03   TOSCA      -                    -                    0 : 
  10   1   3    11      8.6602540E-01     2.0000E-01    8.6605876E-01   9.9725E-01   SPNPRT     -                    -                    0 : 
  10   1   4    11      1.0000000E+00     2.0000E-01    1.0000000E+00   0.0000E+00   SPNPRT     -                    -                    0 : 
 Fit reached penalty value   2.7752E-08

************************************************************************************************************************************

           MAIN PROGRAM :  FIT completed.  Now doing a last run using variable values from FIT. 

************************************************************************************************************************************
      1  Keyword, label(s) :  OBJET                                                 

                          MAGNETIC  RIGIDITY =       7205.178 kG*cm

                                         TRAJECTOIRY SETTING UP

                              OBJET  (1)  BUILT  UP  FROM      10 POINTS 



                                 D         Y(cm)       T(mrd)      Z(cm)       P(mrd)      X(cm)

                     NUMBER         1          10           1           1           1           0


                    SAMPLING      0.0000      0.00        0.00        0.00        0.00        0.00


************************************************************************************************************************************
      2  Keyword, label(s) :  PARTICUL                                              


************************************************************************************************************************************
      3  Keyword, label(s) :  SPNTRK                                                


                SPIN  TRACKING  REQUESTED  

                          PARTICLE  MASS          =    938.2720     MeV/c2
                          GYROMAGNETIC  FACTOR  G =    1.792847    

                          INITIAL SPIN CONDITIONS TYPE  5 :
          TO, PO, A, dA :   0.00000E+00  1.57080E+00  1.70000E-02  1.70000E-03

               WARNING :  INSTALLATION OF KSO=5 NEEDS BE COMPLETED !



                          PARAMETRES  DYNAMIQUES  DE  REFERENCE :
                               BORO   =      7205.178 KG*CM
                               BETA   =    0.917207
                               GAMMA*G =   4.500000


                          POLARISATION  INITIALE  MOYENNE  DU  FAISCEAU  DE       10  PARTICULES :
                               <SX> =     0.000000
                               <SY> =     0.000000
                               <SZ> =     1.000000
                               <S>  =     1.000000

************************************************************************************************************************************
      4  Keyword, label(s) :  SPNPRT                                                



                         Momentum  group  #1 ; average  over 10 particles at this pass : 

                   INITIAL                                           FINAL

      <SX>       <SY>       <SZ>       <|S|>            <SX>       <SY>       <SZ>      <|S|>    <G.gma>    <(SI,SF)>  sigma_(SI,SF)
                                                                                                               (deg)       (deg)
   0.000000   0.000000   1.000000   1.000000         0.000000   0.000000   1.000000   1.000000   4.500000   0.000000   0.000000


                Spin  components  of  each  of  the     10  particles,  and  rotation  angle :

                   INITIAL                                           FINAL

           SX        SY        SZ        |S|         SX        SY        SZ        |S|       GAMMA   (Si,Sf)   (Z,Sf_X)  (Z,Sf)
                                                                                                      (deg.)    (deg.)    (deg.)
                                                                                           (Sf_X : projection of Sf on YZ plane)

 O  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    1
 A  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    2
 B  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    3
 C  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    4
 D  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    5
 E  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    6
 F  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    7
 G  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    8
 H  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000    9
 I  1  0.000000  0.000000  1.000000  1.000000     0.000000  0.000000  1.000000  1.000000      2.5100    0.000    0.000    0.000   10



                Min/Max  components  of  each  of  the     10  particles :

  SX_mi       SX_ma       SY_mi       SY_ma       SZ_mi       SZ_ma       |S|_mi      |S|_ma      p/p_0        GAMMA          I  IEX

 -8.9991E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      1   1
 -8.9987E-03  3.2679E-07 -3.2677E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      2   1
 -8.9989E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      3   1
 -8.9992E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      4   1
 -8.9991E-03  3.2674E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      5   1
 -8.9991E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      6   1
 -8.9989E-03  3.2679E-07 -3.2677E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      7   1
 -8.9985E-03  3.2677E-07 -3.2673E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      8   1
 -8.9986E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      9   1
 -8.9987E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00     10   1

************************************************************************************************************************************
      5  Keyword, label(s) :  FAISCEAU                                              

0                                             TRACE DU FAISCEAU
                                           (follows element #      4)
                                                 10 TRAJECTOIRES

                                   OBJET                                                  FAISCEAU

          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)

O  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.490    0.000    0.000    0.000   0.000000E+00     1
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
A  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.490    0.000    0.000    0.000   0.000000E+00     2
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
B  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.490    0.000    0.000    0.000   0.000000E+00     3
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
C  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.490    0.000    0.000    0.000   0.000000E+00     4
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
D  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.490    0.000    0.000    0.000   0.000000E+00     5
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
E  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.490    0.000    0.000    0.000   0.000000E+00     6
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
F  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.490    0.000    0.000    0.000   0.000000E+00     7
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
G  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.490    0.000    0.000    0.000   0.000000E+00     8
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
H  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.490    0.000    0.000    0.000   0.000000E+00     9
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    
I  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.490    0.000    0.000    0.000   0.000000E+00    10
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    


------
  Characteristics of concentration ellipse (Surface, ALP, BET, <X>, <XP>, #prtcls, #prtcls inside ellips, ratio, space, pass#) : 

   0.0000E+00   0.0000E+00   1.0000E+00  -2.490224E-02   0.000000E+00       10        0    0.000      (Y,T)        11
   0.0000E+00   0.0000E+00   1.0000E+00   0.000000E+00   0.000000E+00       10       10    1.000      (Z,P)        11
   0.0000E+00   0.0000E+00   1.0000E+00   0.000000E+00   1.416766E+03       10        0    0.000      (t,K)        11

(Y,T)  space (units : (cm,rd)   ) :  
      sigma_Y = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_T = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(Z,P)  space (units : (cm,rd)   ) :  
      sigma_Z = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_P = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(t,K)  space (units : (mu_s,MeV)) :  
      sigma_t = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_K = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00


  Beam  sigma  matrix : 

   1.203706E-35   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00

      sqrt(det_Y), sqrt(det_Z) :     0.000000E+00    0.000000E+00    (Note :  sqrt(determinant) = ellipse surface / pi)

************************************************************************************************************************************
      6  Keyword, label(s) :  DRIFT       DRIF                  CSNK                


                              Drift,  length =   -20.00000  cm

TRAJ #1 IEX,D,Y,T,Z,P,S,time :  1  0.000000E+00 -2.490224E+00  0.000000E+00  0.000000E+00  0.000000E+00  -2.0000000E+01  -7.27347E-04
TRAJ #1 SX, SY, SZ, |S| :  1   -3.252263E-07  -3.198021E-08   1.000000E+00   1.000000E+00

 Cumulative length of optical axis =  -0.200000000     m   ;  Time  (for reference rigidity & particle) =   9.455515E-09 s 

************************************************************************************************************************************
      7  Keyword, label(s) :  TOSCA                                                 


     zgoubi.plt                                                                      
      already open...

     Status of MOD.MOD2 is 15.2 ; NDIM = 3 ; number of field data files used is   2.
     Field map set stored in field array HC(IMAP = 1)
     3-D map. MOD=15.   Will sum up  2  field maps, with field coefficient values : 
                 1.100000E+00  3.153769E-01

     ZroBXY OPTION :  absent from map title. BX and BY values in Z=0 plane left as read.

     No  map  file  opened :  was  already  stored.
     Skip  reading  field  map  file :           b_ags-full-coilv5-x06-rerun2-x071-integral-x5y5z10mm.table

     No  map  file  opened :  was  already  stored.
     Skip  reading  field  map  file :           b_ags-full-sold3-only-nodal-x5y5z10mm-wasactually-integral.table
     Restored mesh coordinates for field map #IMAP=   1,  name : b_ags-full-sold3-only-nodal-x5y5z10mm-wasactually-integral.table
     Field from  2 map(s) is combined (summed up) with linear combination coefficient(s) a(i=1-4), respectively) : 
            1.100000E+00  3.153769E-01

     Min/max fields found in map (series) read   :  -4.805113E-02  /   7.401420E-02
       @  X,  Y, Z :   41.0      -7.00       6.00                  /   0.00       6.50       6.50    
     Given normalisation coeffs on field, x, y, z :   9.852015E+00   1.000000E+00   1.000000E+00   1.000000E+00
     this yields min/max normalised fields (kG) : -4.734005E-01                      7.291890E-01
       @  X (cm),  Y (cm), Z (cm) :   41.0      -7.00       6.00   /   0.00       6.50       6.50    

     Length of element,  XL =  3.200000E+02 cm 
                                               from  XI =  -1.600000E+02 cm 
                                               to    XF =   1.600000E+02 cm 

     Nbr of nodes in X = 321;  nbr of nodes in Y =   29
     X-size of mesh =  1.000000E+00 cm ; Y-size =  5.000000E-01 cm
     nber of mesh nodes in Z =   29 ; Step in Z =  0.500000E+00 cm

                     OPTION  DE  CALCUL  :  GRILLE  3-D  A  3*3*3  POINTS , INTERPOLATION  A  L'ORDRE  2

                    Integration step :   2.000     cm

  A    1  1.0000    -2.490     0.000     0.000     0.000          160.000    -2.332     0.001    -0.207     0.000            1
  A    1  1.0000    -2.490     0.000     0.000     0.000          160.000    -2.332     0.001    -0.207     0.000            2
  A    1  1.0000    -2.490     0.000     0.000     0.000          160.000    -2.332     0.001    -0.207     0.000            3
  A    1  1.0000    -2.490     0.000     0.000     0.000          160.000    -2.332     0.001    -0.207     0.000            4
  A    1  1.0000    -2.490     0.000     0.000     0.000          160.000    -2.332     0.001    -0.207     0.000            5
  A    1  1.0000    -2.490     0.000     0.000     0.000          160.000    -2.332     0.001    -0.207     0.000            6
  A    1  1.0000    -2.490     0.000     0.000     0.000          160.000    -2.332     0.001    -0.207     0.000            7
  A    1  1.0000    -2.490     0.000     0.000     0.000          160.000    -2.332     0.001    -0.207     0.000            8
  A    1  1.0000    -2.490     0.000     0.000     0.000          160.000    -2.332     0.001    -0.207     0.000            9
  A    1  1.0000    -2.490     0.000     0.000     0.000          160.000    -2.332     0.001    -0.207     0.000           10


                CONDITIONS  DE  MAXWELL  (     1610.  PAS )  :
                       DIV(B)        LAPLACIEN(B)     ROTATIONNEL(B)
                     7.6853E-15      -9.6179E-16        2.7875E-16
                                     -3.7186E-15       -1.6490E-14
                                     -2.8253E-15        2.6652E-14
                       LAPLACIEN SCALAIRE =   0.000    



     KPOS =  2.  Element  is  mis-aligned  wrt.  the  optical  axis.
          X =   0.000     CM   Y =   0.000     cm,  tilt  angle =   0.00000     RAD


 Cumulative length of optical axis =    3.00000000     m ;  Time  (for ref. rigidity & particle) =   2.109307E-08 s 

************************************************************************************************************************************
      8  Keyword, label(s) :  DRIFT       DRIF                  CSNK                


                              Drift,  length =   -20.00000  cm

TRAJ #1 IEX,D,Y,T,Z,P,S,time :  1  0.000000E+00 -2.352945E+00  1.043808E+00 -1.979380E-01 -4.433070E-01   2.8069523E+02   1.02081E-02
TRAJ #1 SX, SY, SZ, |S| :  1   -8.574959E-03   4.998687E-01   8.660588E-01   1.000000E+00

 Cumulative length of optical axis =    2.80000000     m   ;  Time  (for reference rigidity & particle) =   2.036572E-08 s 

************************************************************************************************************************************
      9  Keyword, label(s) :  REBELOTE                                              


************************************************************************************************************************************
     10  Keyword, label(s) :  FAISCEAU                                              

0                                             TRACE DU FAISCEAU
                                           (follows element #      9)
                                                 10 TRAJECTOIRES

                                   OBJET                                                  FAISCEAU

          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)

O  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     1
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
A  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     2
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
B  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     3
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
C  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     4
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
D  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     5
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
E  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     6
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
F  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     7
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
G  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     8
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
H  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     9
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
I  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02    10
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    


------
  Characteristics of concentration ellipse (Surface, ALP, BET, <X>, <XP>, #prtcls, #prtcls inside ellips, ratio, space, pass#) : 

   0.0000E+00   0.0000E+00   1.0000E+00  -2.352945E-02   1.043808E-03       10       10    1.000      (Y,T)        11
   0.0000E+00   0.0000E+00   1.0000E+00  -1.979380E-03  -4.433070E-04       10        0    0.000      (Z,P)        11
   0.0000E+00   0.0000E+00   1.0000E+00   1.020815E-02   1.416766E+03       10        0    0.000      (t,K)        11

(Y,T)  space (units : (cm,rd)   ) :  
      sigma_Y = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_T = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(Z,P)  space (units : (cm,rd)   ) :  
      sigma_Z = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_P = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(t,K)  space (units : (mu_s,MeV)) :  
      sigma_t = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_K = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00


  Beam  sigma  matrix : 

   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   1.880791E-37   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00

      sqrt(det_Y), sqrt(det_Z) :     0.000000E+00    0.000000E+00    (Note :  sqrt(determinant) = ellipse surface / pi)

************************************************************************************************************************************
     11  Keyword, label(s) :  SPNPRT                                                



                         Momentum  group  #1 ; average  over 10 particles at this pass : 

                   INITIAL                                           FINAL

      <SX>       <SY>       <SZ>       <|S|>            <SX>       <SY>       <SZ>      <|S|>    <G.gma>    <(SI,SF)>  sigma_(SI,SF)
                                                                                                               (deg)       (deg)
   0.000000   0.000000   1.000000   1.000000        -0.008575   0.499869   0.866059   1.000000   4.500000  29.996180   0.000001


                Spin  components  of  each  of  the     10  particles,  and  rotation  angle :

                   INITIAL                                           FINAL

           SX        SY        SZ        |S|         SX        SY        SZ        |S|       GAMMA   (Si,Sf)   (Z,Sf_X)  (Z,Sf)
                                                                                                      (deg.)    (deg.)    (deg.)
                                                                                           (Sf_X : projection of Sf on YZ plane)

 O  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    1
 A  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    2
 B  1  0.000000  0.000000  1.000000  1.000000    -0.008574  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    3
 C  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    4
 D  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    5
 E  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    6
 F  1  0.000000  0.000000  1.000000  1.000000    -0.008574  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    7
 G  1  0.000000  0.000000  1.000000  1.000000    -0.008574  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    8
 H  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499868  0.866059  1.000000      2.5100   29.996   29.993   29.996    9
 I  1  0.000000  0.000000  1.000000  1.000000    -0.008574  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996   10



                Min/Max  components  of  each  of  the     10  particles :

  SX_mi       SX_ma       SY_mi       SY_ma       SZ_mi       SZ_ma       |S|_mi      |S|_ma      p/p_0        GAMMA          I  IEX

 -8.9991E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      1   1
 -8.9987E-03  3.2679E-07 -3.2677E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      2   1
 -8.9989E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      3   1
 -8.9992E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      4   1
 -8.9991E-03  3.2674E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      5   1
 -8.9991E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      6   1
 -8.9989E-03  3.2679E-07 -3.2677E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      7   1
 -8.9985E-03  3.2677E-07 -3.2673E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      8   1
 -8.9986E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      9   1
 -8.9987E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00     10   1

************************************************************************************************************************************

     12   Keyword FIT[2] is skipped since this is the (end of) last run following the fitting procedure.

          Now carrying on beyond FIT keyword.


************************************************************************************************************************************
     13  Keyword, label(s) :  FAISCEAU                                              

0                                             TRACE DU FAISCEAU
                                           (follows element #     12)
                                                 10 TRAJECTOIRES

                                   OBJET                                                  FAISCEAU

          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)          D       Y(CM)    T(MR)    Z(CM)    P(MR)      S(CM)

O  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     1
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
A  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     2
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
B  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     3
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
C  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     4
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
D  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     5
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
E  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     6
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
F  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     7
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
G  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     8
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
H  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02     9
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    
I  1   1.0000    -2.490     0.000     0.000     0.000       0.0000    1.0000   -2.353    1.044   -0.198   -0.443   2.806952E+02    10
               Time of flight (mus) :  1.02081460E-02 mass (MeV/c2) :   938.272    


------
  Characteristics of concentration ellipse (Surface, ALP, BET, <X>, <XP>, #prtcls, #prtcls inside ellips, ratio, space, pass#) : 

   0.0000E+00   0.0000E+00   1.0000E+00  -2.352945E-02   1.043808E-03       10       10    1.000      (Y,T)        11
   0.0000E+00   0.0000E+00   1.0000E+00  -1.979380E-03  -4.433070E-04       10        0    0.000      (Z,P)        11
   0.0000E+00   0.0000E+00   1.0000E+00   1.020815E-02   1.416766E+03       10        0    0.000      (t,K)        11

(Y,T)  space (units : (cm,rd)   ) :  
      sigma_Y = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_T = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(Z,P)  space (units : (cm,rd)   ) :  
      sigma_Z = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_P = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00

(t,K)  space (units : (mu_s,MeV)) :  
      sigma_t = sqrt(Surface/pi * BET) =   0.000000E+00
      sigma_K = sqrt(Surface/pi * (1+ALP^2)/BET) =   0.000000E+00


  Beam  sigma  matrix : 

   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00
   0.000000E+00   0.000000E+00   1.880791E-37   0.000000E+00
   0.000000E+00   0.000000E+00   0.000000E+00   0.000000E+00

      sqrt(det_Y), sqrt(det_Z) :     0.000000E+00    0.000000E+00    (Note :  sqrt(determinant) = ellipse surface / pi)

************************************************************************************************************************************
     14  Keyword, label(s) :  SPNPRT                                                



                         Momentum  group  #1 ; average  over 10 particles at this pass : 

                   INITIAL                                           FINAL

      <SX>       <SY>       <SZ>       <|S|>            <SX>       <SY>       <SZ>      <|S|>    <G.gma>    <(SI,SF)>  sigma_(SI,SF)
                                                                                                               (deg)       (deg)
   0.000000   0.000000   1.000000   1.000000        -0.008575   0.499869   0.866059   1.000000   4.500000  29.996180   0.000001


                Spin  components  of  each  of  the     10  particles,  and  rotation  angle :

                   INITIAL                                           FINAL

           SX        SY        SZ        |S|         SX        SY        SZ        |S|       GAMMA   (Si,Sf)   (Z,Sf_X)  (Z,Sf)
                                                                                                      (deg.)    (deg.)    (deg.)
                                                                                           (Sf_X : projection of Sf on YZ plane)

 O  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    1
 A  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    2
 B  1  0.000000  0.000000  1.000000  1.000000    -0.008574  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    3
 C  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    4
 D  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    5
 E  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    6
 F  1  0.000000  0.000000  1.000000  1.000000    -0.008574  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    7
 G  1  0.000000  0.000000  1.000000  1.000000    -0.008574  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996    8
 H  1  0.000000  0.000000  1.000000  1.000000    -0.008575  0.499868  0.866059  1.000000      2.5100   29.996   29.993   29.996    9
 I  1  0.000000  0.000000  1.000000  1.000000    -0.008574  0.499869  0.866059  1.000000      2.5100   29.996   29.993   29.996   10



                Min/Max  components  of  each  of  the     10  particles :

  SX_mi       SX_ma       SY_mi       SY_ma       SZ_mi       SZ_ma       |S|_mi      |S|_ma      p/p_0        GAMMA          I  IEX

 -8.9991E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      1   1
 -8.9987E-03  3.2679E-07 -3.2677E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      2   1
 -8.9989E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      3   1
 -8.9992E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      4   1
 -8.9991E-03  3.2674E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      5   1
 -8.9991E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      6   1
 -8.9989E-03  3.2679E-07 -3.2677E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      7   1
 -8.9985E-03  3.2677E-07 -3.2673E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      8   1
 -8.9986E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00      9   1
 -8.9987E-03  3.2679E-07 -3.2679E-07  5.0029E-01  8.6582E-01  1.0000E+00  1.0000E+00  1.0000E+00  1.00000E+00  2.50997E+00     10   1

************************************************************************************************************************************
     15  Keyword, label(s) :  END                                                   


************************************************************************************************************************************

          Pgm zgoubi : Execution ended upon key  END       

************************************************************************************************************************************

                    Saving new version of data file to zgoubi.FIT.out.dat, with variables updated.

                    Updated version of input data file saved in zgoubi.FIT.out.dat
   
            ZGOUBI RUN COMPLETED. 

  Zgoubi, author's dvlpmnt version.
  Job  started  on  21-01-0017,  at  07:23:55 
  JOB  ENDED  ON    21-01-0017,  AT  07:23:59 

   CPU time, total :     4.38427400000000     
