C      subroutine searchCO(nCO,xK,xiDeg)
C Starting from initial coordinates near closed orbits, as read from input file 
C zgoubi.dat (possibly generated by geneMap), look for precise co's
C works like searchCO, yet does vertical co search in addition (flag kaseV=2) 
C (note : this is in case v_co not zero due for instance to some V kicker, or defects...)
      implicit double precision (a-h,o-z)

      parameter (lunR=11,lunW=12)
      character(1) let
      character(300) txt300, txt300c, cmnd
      parameter (nCOmx=10001, maxIter=20)

      dimension x(nCOmx),xp(nCOmx),z(nCOmx),
     >                   zp(nCOmx),s(nCOmx),d(nCOmx),let(nCOmx)
      dimension clorb(7,nCOmx)
      character cmmnd*110

      logical ok, strcon, first, idluni
      data ok, first / .false., .true. /

      integer debstr, finstr

      logical reb, empty

c      character(30) tilde
c      parameter (tilde = '/home/owl/fmeot')
      character(1) tilde
      parameter (tilde = '~')
      character(300) exec, cmndZ
      parameter (exec = 
     >   '/zgoubi/source/zgoubi')

      character txtStep*40, txtSample*40       
      data txtStep, txtSample / ' 0.02  stepSize',    
     > '.01 .01 .01 .01 0. .001         ' /

C Requested precision on co (cm, mrad)
C Careful here :  PREC MUST BE COMPATIBLE with precision on x and xp as read in zgoubi.res
      data precX, precXp / .01d0, .01d0 /     ! zgoubi units cm, mrad
C      data precX, precXp / .0001d0, .001d0 /
      data  kaseV / 2 /
      data  dpp / 1.d-3 /

      cmndZ = tilde(debstr(tilde):finstr(tilde))//
     >    exec(debstr(exec):finstr(exec))

      if (idluni(lunIn)) then
        open(unit=lunIn,file='searchCO.In',err=25)
        read(lunIn,*,err=24,end=24) kaseVi, dppi
        read(lunIn,*,err=24,end=24) precXi, precXpi 
        kaseV= kaseVi 
        dpp  = dppi
        precX  = precXi
        precXp = precXpi 
        goto 26
 24    continue
        rewind(lunIn)
        write(lunIn,*) kaseV, dpp,'  kaseV, dpp    created by searchCO'      
        write(lunIn,*) precX, precXp,'  precX, precXp'  
 26     continue
 25     continue
        close(lunIn)
      endif

      open(unit=lunR,file='zgoubi_searchCO-In.dat')
c      open(unit=lunW,file='zgoubi.dat')

C 182  continue
C        read(lunR,fmt='(a)',end=183,err=183) txt300
C        if(empty(txt300)) goto 182
C        txt300 = txt300(debstr(txt300):finstr(txt300))
C        if(txt300(1:1) .eq. '!') goto 182
C        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
C      goto 182
C 183  continue
C      close(lunw)
C      cmnd = 'cp -f zgoubi.dat zgoubi_searchCO-In.dat'
C      call system(cmnd)

      cl9 = 2.99792458D8 / 1.d9

      jo = 1
      jok = 0
 2    continue

        rewind(lunR)
        open(unit=lunW,file='zgoubi.dat')
        rewind(lunW)

C Read till "KOBJ"
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') 
     >  'Data generated by searchCO '

        txt300 = ' '
        dowhile(
     >  .not. strcon(txt300(debstr(txt300):finstr(txt300)),'''OBJET''',
     >  7,IS)
     >  .and. 
     >  .not.strcon(txt300(debstr(txt300):finstr(txt300)),'''MCOBJET''',
     >  9,IS))
          read(lunR,fmt='(a)') txt300
          write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
c          write(*,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
c             read(*,*)
        enddo 
c        read(lunR,fmt='(a)') txt300
c        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
c        read(lunR,fmt='(a)') txt300
c        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        read(txt300,*) BORO
        !!!write(*,*) ' Reference rigidity BRho = ',BORO/1000.d0,' T.m' 
        read(lunR,*) XOBJ       
        KOBJ = INT(XOBJ)
        if(KOBJ .eq. 2 ) then 
          write(lunW,*) KOBJ
C Read till "IMAX IMAXT"
          read(lunR,*) nCO, imaxt
          if(nCO.gt.nCOmx) stop ' Too many co''s...'
          if(nCO.lt.1) stop ' No  co in zgoubi_searchCO-In.dat !!'
          txt300 = ' 1  1'
          write(lunW,*) txt300(debstr(txt300):finstr(txt300))
C Read all initial traj present in zgoubi_searchCO-In.dat
          do i=1,nCO
            read(lunR,*) x(i),xp(i),z(i),zp(i),s(i),d(i),let(i)
          enddo
C Retains only one initial traj at a time
C        write(lunW,fmt='(1p,2e14.6,2e9.1,e9.1,e14.7,4a,i4)') 
          write(lunW,fmt='(1p,4e14.6,e9.1,e14.7,4a,i4)') 
     >    x(jo),xp(jo),z(jo),zp(jo),s(jo),d(jo),' ','''',let(jo),'''',jo
          write(6,*) 
          write(6,*) ' ---------    New trajectory :'
C          write(6,fmt='(1p,2e14.6,2e9.1,e9.1,e14.7,4a,i4)') 
          write(6,fmt='(1p,4e14.6,e9.1,e14.7,4a,i4)') 
     >    x(jo),xp(jo),z(jo),zp(jo),s(jo),d(jo),' ','''',let(jo),'''',jo
          write(6,*)
C write first line with "1's" 
          read(lunR,fmt='(a)',end=10) txt300
          write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
        else
 27       continue
          read(lunR,fmt='(a)') txt300
          txt300 = txt300(debstr(txt300):finstr(txt300))
          if(txt300(1:1) .eq. '''') then 
            backspace(lunR)
            KOBJ = 2
            write(lunW,*) KOBJ
            nCO = 2
            imaxt = 1
            write(lunW,*) nCO, imaxt
            x(1)= 0.d0
            xp(1)= 0.d0
            z(1)= 0.d0
            zp(1)= 0.d0
            s(1)= 0.d0
            d(1)= 1.d0
            let(1)= 'o'
            x(2)= 0.d0
            xp(2)= 0.d0
            z(2)= 0.d0
            zp(2)= 0.d0
            s(2)= 0.d0
            d(2)= 1.d0 + dpp
            let(2)= 'p'
            write(lunW,fmt='(1p,4e14.6,e9.1,e14.7,4a,i4)') 
     >    x(jo),xp(jo),z(jo),zp(jo),s(jo),d(jo),' ','''',let(jo),'''',jo
            write(6,*) 
            write(6,*) ' ---------    New trajectory :'
            write(6,fmt='(1p,4e14.6,e9.1,e14.7,4a,i4)') 
     >    x(jo),xp(jo),z(jo),zp(jo),s(jo),d(jo),' ','''',let(jo),'''',jo
            write(6,*)
C write line with a "1" 
            write(lunW,*) ' 1 '
          else
            goto 27
          endif
        endif

        txt300    = '''PICKUPS'''
        write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
        txt300    = ' 1'
        write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
        txt300    = ' #Start'
        write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
        txt300    =  '''MARKER''   #Start '
        write(lunW,*) txt300(debstr(txt300):finstr(txt300))   

C Completes zgoubi.dat with the rest of zgoubi_searchCO-In.dat
 1      continue
          read(lunR,fmt='(a)',end=10) txt300

c             write(*,*) txt300
c              read(*,*)

          if(strcon(txt300,'1 1 1 1 1 1 1 1 1 1',19,
     >                                              IS)) then 
C           do not write possible subsquent lines of "1's"

          elseif(strcon(txt300,'''PICKUPS''',9,
     >                                      IS)) then 
            read(lunR,fmt='(a)',end=10) txt300
            read(lunR,fmt='(a)',end=10) txt300

          elseif(strcon(txt300,'''OPTICS''',8,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''MARKER''',8,
     >                                    IS)) then 
            if(strcon(txt300,'#Start',6,
     >                                    IS)) then 
            endif

          elseif(strcon(txt300,'''PARTICUL''',10,
     >                                           IS)) then 
            write(lunW,*) txt300(debstr(txt300):finstr(txt300))               
            read(lunR,fmt='(a)',end=10) txt300
            write(lunW,*) txt300(debstr(txt300):finstr(txt300))               
            read(txt300,*) am,q
            write(6,*) ' particle mass and charge : ', am, q
            P0 = BORO*CL9

          elseif(strcon(txt300,'''TWISS''',7,
     >                                       IS)) then
            read(lunR,fmt='(a)',end=10) txt300

          elseif(strcon(txt300,'''FIT''',5,
     >                                       IS)
     >      .or. strcon(txt300,'''FIT2''',6,
     >                                       IS)) then
            read(lunR,*,end=10) IV
            do ii = 1, iv
              read(lunR,fmt='(a)',end=10) txt300
            enddo
            read(lunR,*,end=10) IC
            do ii = 1, ic
              read(lunR,fmt='(a)',end=10) txt300
            enddo

          elseif(strcon(txt300,'''REBELOTE''',10,
     >                                         IS)) then
            goto 10

          elseif(strcon(txt300,'''END''',5,
     >                                       IS)) then
            goto 10

          elseif(strcon(txt300,'''FIN''',5,
     >                                       IS)) then
            goto 10

          else
C                write(*,*)  txt300(debstr(txt300):finstr(txt300))
                write(lunW,*) txt300(debstr(txt300):finstr(txt300))               

          endif

        goto 1

 10     continue

              txt300 = '''REBELOTE'''
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
C              txt300 = '9   0.2  99'
              txt300 = '29   0.1  99'
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              txt300 = '''END'''
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))

c              write(*,*) txt300
c              read(*,*)
        close(lunW)

        call avrorb(jo,maxIter,kaseV,cmndZ, 
     >                xav,xpav,zav,zpav,sav,dav,tav,kex,ok,precX,precXp)
 
       if(ok) then 
          jok = jok + 1
          write(6,*) 
          write(6,fmt='(a,i4,a,a,2f9.4,a,a,i4,a)') 
     >    ' ---------    Found ',jok,' average orbits ',
     >    '(precision dx, dx'' : ',precX,precXp,' cm, mrad) ; ',
     >    '  now c.o. #',jo,' :'
C          write(6,fmt='(1p,2e14.6,2e9.1,e9.1,e12.4,e14.6)') 
          write(6,fmt='(1p,4e14.6,e9.1,e12.4,e14.6)') 
     >                          xav,xpav,zav,zpav,sav,dav,tav
          write(6,*)
          clorb(1,jok) = xav
          clorb(2,jok) = xpav
          if(kaseV.eq.0) then
            clorb(3,jok) = .0
            clorb(4,jok) = .0 
          elseif(kaseV.eq.1) then
            clorb(3,jok) = .0001 !!!!!zav
            clorb(4,jok) = .0 !!!!zpav
          elseif(kaseV.eq.2) then
            clorb(3,jok) = zav
            clorb(4,jok) = zpav
          else
          endif
          clorb(5,jok) = .0 !!!sav
          clorb(6,jok) = dav
          clorb(7,jok) = tav
        endif

        write(6,*) ' jo / nCO :    ', jo,' / ',nCO
        if(jo.ge. nCO) goto 60
        jo = jo+1
      goto 2

 60   continue
      close(lunR)

Create  zgoubi_searchCO-Out.dat  containing computed closed orbits
      open(unit=lunR,file='zgoubi_searchCO-In.dat')
      open(unit=lunW,file='zgoubi_searchCO-Out.dat')


C Read/write till "KOBJ"
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') 
     >  'Data generated by searchCO '
        txt300 = ' '
        dowhile(
     >  .not. strcon(txt300(debstr(txt300):finstr(txt300)),'''OBJET''',
     >  7,IS)
     >  .and. 
     >  .not.strcon(txt300(debstr(txt300):finstr(txt300)),'''MCOBJET''',
     >  9,IS))
          read(lunR,fmt='(a)') txt300
          write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        enddo 
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        read(txt300,*) BORO
        !!!write(*,*) ' Reference rigidity BRho = ',BORO/1000.d0,' T.m' 
        read(lunR,*) XOBJ       
        KOBJ = INT(XOBJ)
        write(lunW,fmt='(a)') ' 2 '
C Read rest of OBJET data
 28     continue
          read(lunR,fmt='(a)') txt300
          txt300 = txt300(debstr(txt300):finstr(txt300))
          if(txt300(1:1) .ne. '''') goto 28
          backspace(lunR)
C Write "IMAX IMAXT"
        write(lunW,fmt='(i3,a)') jok,'  1'
C Write all co coordinates (clorb(i,j)) into zgoubi_searchCO-Out.dat
        txt300 = ' 1 '
        do j=1,jok
          pj = p0 * clorb(6,j)
          Tj = sqrt(pj*pj+am*am) - am
          write(lunW,fmt='(1p,4e14.6,e9.1,e16.8,4a,f12.2,a)') 
     >    clorb(1,j), clorb(2,j), clorb(3,j), clorb(4,j),
     >    clorb(5,j), clorb(6,j),' ','''',let(j),''' ',Tj/10.,' MeV'
          txt300 = txt300(debstr(txt300):finstr(txt300))//' 1'
        enddo
C Write line of '1's
        write(lunW,fmt='(a)') ' '//txt300(2:finstr(txt300))

            txt300 = '''FAISCEAU'''
            write(lunW,*) txt300(debstr(txt300):finstr(txt300))
      txt300 = '''FAISTORE'''
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      txt300 = '     b_zgoubi.fai  all'
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      txt300 = '  1 '
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      txt300 = '''MARKER''     #Start '
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))

C Completes zgoubi_searchCO-Out.dat with the rest of zgoubi_searchCO-In.dat
      reb = .false.
 61   continue
        read(lunR,fmt='(a)',end=62) txt300
        txt300 = txt300(debstr(txt300):finstr(txt300))
        if(strcon(txt300,'''MARKER''',8,
     >                                  IS)) then 
          if(strcon(txt300,'#Start',6,
     >                                IS)) then 
            goto 61
          elseif(strcon(txt300,'#End',4,
     >                                    IS)) then 
            goto 61
          endif

        elseif(strcon(txt300,'''FAISCNL''',9,
     >                                       IS)) then 
          read(lunR,fmt='(a)') txt300
          goto 61

        elseif(strcon(txt300,'''OPTICS''',8,
     >                                       IS)) then 
          read(lunR,fmt='(a)') txt300
          goto 61

        elseif(strcon(txt300,'''FAISTORE''',10,
     >                                       IS)) then 
          read(lunR,fmt='(a)') txt300
          read(lunR,fmt='(a)') txt300
          goto 61

        elseif(strcon(txt300,'''FAISCEAU''',10,
     >                                     IS)) then
          goto 62
        elseif(strcon(txt300,'''REBELOTE''',10,
     >                                IS)) then 
          read(lunR,fmt='(a)',end=62) txt300
          goto 62

        elseif(strcon(txt300,'''TWISS''',7,
     >                                     IS)) then 
          read(lunR,fmt='(a)',end=62) txt300
          goto 62

        elseif(strcon(txt300,'''END''',5,
     >                                     IS)) then
          goto 62

        elseif(strcon(txt300,'''FIN''',5,
     >                                     IS)) then
          goto 62
        endif

        write(lunW,*) txt300(debstr(txt300):finstr(txt300))

      goto 61

 62   continue 
            txt300 = '''FAISCEAU'''
            write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            txt300 = '''MARKER''     #End '
            write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            txt300 = '''REBELOTE'''
            write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            txt300 = ' 0   0.2  99'
            write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            txt300 = '''END'''
            write(lunW,*) txt300(debstr(txt300):finstr(txt300))
      close(lunR)
      close(lunW)

Create  zgoubi_searchCO-Out_TrkFourier.dat  containing computed closed orbits + epsilon
      open(unit=lunR,file='zgoubi_searchCO-In.dat')
      open(unit=lunW,file='zgoubi_searchCO-Out_TrkFourier.dat')

C Read/write till "KOBJ"
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') 
     >  'Data generated by searchCO '
        txt300 = ' '
        dowhile(
     >  .not. strcon(txt300(debstr(txt300):finstr(txt300)),'''OBJET''',
     >  7,IS)
     >  .and. 
     >  .not.strcon(txt300(debstr(txt300):finstr(txt300)),'''MCOBJET''',
     >  9,IS))
          read(lunR,fmt='(a)') txt300
          write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        enddo 
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        read(txt300,*) BORO
        !!!write(*,*) ' Reference rigidity BRho = ',BORO/1000.d0,' T.m' 
        read(lunR,*) XOBJ       
        KOBJ = INT(XOBJ)
        write(lunW,fmt='(a)') ' 2 '
C Read rest of OBJET data
 29     continue
          read(lunR,fmt='(a)') txt300
          txt300 = txt300(debstr(txt300):finstr(txt300))
          if(txt300(1:1) .ne. '''') goto 29
          backspace(lunR)
C Write "IMAX IMAXT"
        write(lunW,fmt='(i3,a)') jok,'  1'
C Write all co coordinates (clorb(i,j)) into zgoubi_searchCO-Out_TrkFourier.dat
        do j=1,jok
          pj = p0 * clorb(6,j)
          Tj = sqrt(pj*pj+am*am) - am
          xx = clorb(1,j) + .01   !cm
          if (abs(xx).lt.1d-3) xx=1d-3 
          zz = clorb(3,j) + .01   !cm
          if (abs(zz).lt.1d-3) zz=1d-3 
          write(lunW,fmt='(1p,4e14.6,e9.1,e16.8,4a,f12.2,a)') 
     >    xx, clorb(2,j), zz, clorb(4,j),
     >    clorb(5,j), clorb(6,j),' ','''',let(j),''' ',Tj/10.,' MeV'
        enddo
C Create lines of 1s
      k10 = jok/10
      kk = jok - 10*k10
      txt300 = '1 1 1 1 1 1 1 1 1 1 '
      do ii = 1, k10
        write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      enddo
      if(kk.ne.0) write(lunW,*) txt300(debstr(txt300):finstr(txt300))   

      txt300 = '''FAISTORE'''
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      txt300 = '     b_zgoubi.fai  #Start '
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      txt300 = '  1 '
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
      txt300 = '''MARKER''     #Start '
      write(lunW,*) txt300(debstr(txt300):finstr(txt300))

C Completes zgoubi_searchCO-Out_TrkFourier.dat with the rest of zgoubi_searchCO-In.dat
 18   continue
          read(lunR,fmt='(a)',end=13) txt300
          txt300 = txt300(debstr(txt300):300)

          if(strcon(txt300,'''SPNTRK''',8,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300
            if(txt300(debstr(txt300):debstr(txt300)) .eq. '''') 
     >      write(lunW,*) txt300(debstr(txt300):finstr(txt300))

          elseif(strcon(txt300,'''OPTICS''',8,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''PICKUPS''',9,
     >                                       IS)) then 

            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''SPNPRNL''',9,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''SPNSTORE''',10,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''FAISCNL''',9,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''FAISTORE''',10,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''MARKER''',8,
     >                                        IS)) then 
            txt300c = txt300(IS+8:300-8)
            txt300c = txt300c(debstr(txt300c):debstr(txt300c)+6)
            if(txt300c.eq.'#Start') then
            elseif(txt300c.eq.'#End') then
            else              
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
            endif

          elseif(strcon(txt300,'''CAVITE''',8,
     >                                        IS)) then
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              read(lunR,*,end=13) xcav
              write(lunW,*) ' 0 ', xcav
              read(lunR,fmt='(a)',end=13) txt300
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              read(lunR,fmt='(a)',end=13) txt300
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))

          elseif(strcon(txt300,'''REBELOTE''',10,
     >                                         IS)) then
            read(lunR,fmt='(a)',end=13) txt300

          elseif(strcon(txt300,'''TWISS''',7,
     >                                       IS)) then 
            read(lunR,fmt='(a)') txt300

          elseif(strcon(txt300,'''END''',5,
     >                                       IS)) then

            goto 11
          elseif(strcon(txt300,'''FIN''',5,
     >                                       IS)) then

            goto 11
          else
            
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
          endif

        goto 18

 11     continue
              txt300 = '''MARKER''   #End'
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              txt300 = '''REBELOTE'''
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              txt300 = '299  0.2  99'
              write(lunW,*) txt300(debstr(txt300):finstr(txt300))
              txt300 = '''END'''
              write(lunW,*) txt300(debstr(txt300):finstr(txt300)) 

 13   continue
      write(*,*) ' '
      write(*,*) ' End of  input file  zgoubi_searchCO-In.dat  reached,'
     >,' file   zgoubi_searchCO-Out_TrkFourier.dat completed.'
      write(*,*) ' ------------'
      write(*,*) ' '
      close(lunR)
      close(lunW)

      write(*,*) ' '
      write(*,*) '--------------'
      write(*,fmt='(a,i2,a,i2,a)') 
     >'zgoubi_searchCO-Out_TrkFourier.dat contains ',
     >jok,' co''s below (over ',nCO,' trajectories launched) :'
      zj = 0.d0
      phij = 0.d0
      do j=1,jok
        pj = p0 * clorb(6,j)
        Tj = sqrt(pj*pj+am*am) - am
C        write(6,fmt='(1p, 2e14.6, 2e9.1, e16.8,
        write(6,fmt='(1p, 4e14.6, e16.8,
     >        e14.6, 4a, f12.2, a)') 
C     >        2e12.4, 4a, f12.2, a)') 
     >  clorb(1,j), clorb(2,j), clorb(3,j), clorb(4,j),
     >  clorb(5,j), clorb(6,j),    !!!!!!!clorb(7,j),
     >        ' ','''',let(j),''' ',Tj/10.,' MeV'
      enddo
      write(*,*) ' '
      if(first) then
        call system('rm -f searchCO.out_COs_old')
        call system('mv -f searchCO.out_COs  searchCO.out_COs_old')
        first = .false.
      endif
      open(unit=33,file='searchCO.temp')
      write(33,*) '# Y, T, Z, P, X, p/p0, Time, tag, Ekin/MeV'
      do j=1,jok
        pj = p0 * clorb(6,j)
        Tj = sqrt(pj*pj+am*am) - am
C        write(33,fmt='(1p, 2e14.6, 2e9.1, e16.8,
        write(33,fmt='(1p, 4e14.6, e16.8,
     >        e13.5, e16.8, 4a, f12.2, a, 2e12.4)') 
     >  clorb(1,j), clorb(2,j), clorb(3,j), clorb(4,j),
     >  clorb(5,j), clorb(6,j), clorb(7,j),
     >       ' ','''',let(j),''' ',Tj/10.,' MeV' !,xK,xiDeg
      enddo
      write(33,*) ' '
      close(33)
      call system('cat searchCO.temp >> searchCO.out_COs')
      call system('rm searchCO.temp')

Create zgoubi_searchCO-Out_MATRIX.dat including MATRIX and containing closed orbits
      open(unit=lunR,file='zgoubi_searchCO-In.dat')
      open(unit=lunW,file='zgoubi_searchCO-Out_MATRIX.dat')

C Read/write till "KOBJ"
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') 
     >  'Data generated by searchCO '
        txt300 = ' '
        dowhile(
     >  .not. strcon(txt300(debstr(txt300):finstr(txt300)),'''OBJET''',
     >  7,IS)
     >  .and. 
     >  .not.strcon(txt300(debstr(txt300):finstr(txt300)),'''MCOBJET''',
     >  9,IS))
          read(lunR,fmt='(a)') txt300
          write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        enddo 
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        read(txt300,*) BORO
        !!!write(*,*) ' Reference rigidity BRho = ',BORO/1000.d0,' T.m' 
        read(lunR,fmt='(a)') txt300
        if    (jok.lt.  1) then 
          if (idluni(itemp)) then
            open(unit=itemp,file='searchCO.temp')
            write(itemp,*) ' 0   CO out of searchCO !'
            close(itemp)
          endif
          stop ' Prgrm searchCO. No CO found. '
        elseif(jok.eq.  1) then 
          write(lunW,fmt='(a)') '5'
        elseif(jok.le.  9) then 
          write(lunW,fmt='(a3,I1)') '5.0',jok
        elseif(jok.le. 99) then
          write(lunW,fmt='(a2,I2)') '5.',jok
        else
          stop ' Prgrm searchCO. Too many co''s'
        endif
C Read "IMAX IMAXT", write sampling
        read(lunR,fmt='(a)') txt300
C Attention : too small dx, dz yield fluctuations in tunes due to truncation
        write(lunW,*) txtSample
C Write co coordinates (clorb(i,j)) into zgoubi_searchCO-Out_MATRIX.dat
        zj = 0.d0
        phij = 0.d0
        ppmi = 1.d10
        do j=1,jok
          read(lunR,fmt='(a)') txt300
          pj = p0 * clorb(6,j)
          Tj = sqrt(pj*pj+am*am) - am
          write(lunW,fmt='(1p,4e14.6,e9.1,e16.8,4a,f12.2,a)') 
     >    clorb(1,j), clorb(2,j), clorb(3,j), clorb(4,j),
     >    clorb(5,j), clorb(6,j),' ','''',let(j),''' ',Tj/10.,' MeV'
          if(abs(1.d0-clorb(6,j)) .lt. ppmi) then
            ppmi = abs(1.d0-clorb(6,j)) 
            jppmi = j
          endif 
        enddo
        do j=1,nCO-jok
          read(lunR,fmt='(a)') txt300
        enddo
C Completes zgoubi_searchCO-Out_MATRIX.dat with the rest of zgoubi_searchCO-In.dat
C except for introducing MATRIX

C------- First get read of '1 1 1 1 ...'
 619    read(lunR,fmt='(a)') txt300
        txt300 = txt300(debstr(txt300):finstr(txt300))
        if(txt300(1:1).ne.'''') then 
          goto 619
        else
          backspace(lunR)
        endif

 611    continue
        read(lunR,fmt='(a)',end=621,err=621) txt300

        if(strcon(txt300,'''TWISS''',7,
     >                                       IS)) then 
C          skip
          read(lunR,fmt='(a)') txt300

        elseif(strcon(txt300,'''END''',5,
     >                               IS)
     >  .or. strcon(txt300,'''FIN''',5,
     >                               IS))   then 
          write(lunW,*) '''MATRIX'''
          write(lunW,*) ' 1  11'
          write(lunW,*) '''FAISCEAU'''
          write(lunW,*) '''END'''
          GOTO 621
        elseif(strcon(txt300,'''MATRIX''',8,
     >                                       IS)) then 
C          skip
          read(lunR,fmt='(a)',end=621,err=621) txt300
        elseif(strcon(txt300,'''REBELOTE''',10,
     >                                         IS)) then 
C          skip
          read(lunR,fmt='(a)',end=621,err=621) txt300
        elseif(strcon(txt300,'stepSize',8,
     >                                        IS)) then 
          write(lunW,*) txtStep
        else
          write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
        endif
      goto 611

 621  close(lunR)
      close(lunW)

Compute matrices so to draw various first order paramaters
      cmnd = 'cp -f zgoubi_searchCO-Out_MATRIX.dat zgoubi.dat'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
      write(*,*) '++++++ ',cmndZ
      call system(cmndZ)
      cmnd = 'cp -f zgoubi.res zgoubi_searchCO-Out_MATRIX.res'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
      cmnd = '~/zgoubi/struct/tools/tunesFromMATRIX/tunesFromMatrix'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)

      open(unit=lunR,file='tunesFromMatrix_LW.out')
      read(lunR,fmt='(a)') txt300
      do j = 1, jppmi
        read(lunR,*) xcom, xpcom, 
     >  zcom, zpcom, pathm,dpcom,tofm, 
     >  alfxm, betxm, alfzm, betzm,alflm, betlm,
     >  Dxm, Dpxm, Dzm, Dpzm, Dlm, Dplm, 
     >  XNUm, ZNUm, smum, EKinm
      enddo
      close(lunR)

Create zgoubi_searchCO-Out_BETA.dat including OPTICS and containing closed orbits
      open(unit=lunR,file='zgoubi_searchCO-In.dat')
      open(unit=lunW,file='zgoubi_searchCO-Out_BETA.dat')

C Read/write till "KOBJ"
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') 
     >  'Data generated by searchCO '
        txt300 = ' '
        dowhile(
     >  .not. strcon(txt300(debstr(txt300):finstr(txt300)),'''OBJET''',
     >  7,IS)
     >  .and. 
     >  .not.strcon(txt300(debstr(txt300):finstr(txt300)),'''MCOBJET''',
     >  9,IS))
          read(lunR,fmt='(a)') txt300
          write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        enddo 
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        read(txt300,*) BORO
        !!!write(*,*) ' Reference rigidity BRho = ',BORO/1000.d0,' T.m' 
        read(lunR,*) XOBJ       
        write(lunW,fmt='(a4)') '5.01'
C Read "IMAX IMAXT", write sampling
        read(lunR,fmt='(a)') txt300
C Attention : too small dx, dz yield fluctuations in tunes due to truncation
        write(lunW,*) txtSample
C Write co coordinates (clorb(i,jppmi)) 
        zj = 0.d0
        phij = 0.d0
        do j=1,jok
          read(lunR,fmt='(a)') txt300
          if(j.eq.jppmi) then
            pj = p0 * clorb(6,j)
            Tj = sqrt(pj*pj+am*am) - am
            write(lunW,fmt='(1p,4e14.6,e9.1,e16.8,4a,f12.2,a)') 
     >      clorb(1,j), clorb(2,j), clorb(3,j), clorb(4,j),
     >      clorb(5,j), clorb(6,j),' ','''',let(j),''' ',Tj/10.,' MeV'
          endif
        enddo
        do j=1,nCO-jok
          read(lunR,fmt='(a)') txt300
        enddo
C Write optical functions
        write(lunW,149) 
     >  alfxm, betxm, alfzm, betzm, alflm, betlm,
     >  Dxm, Dpxm, Dzm, Dpzm
 149    FORMAT(1P,10(1x,E10.3))
C Completes zgoubi_searchCO-Out_BETA.dat with the rest of zgoubi_searchCO-In.dat
C except for introducing OPTICS and for some cleaning

C------- First get read of '1 1 1 1 ...'
 719    read(lunR,fmt='(a)') txt300
        txt300 = txt300(debstr(txt300):finstr(txt300))
        if(txt300(1:1).ne.'''') then 
          goto 719
        else
          backspace(lunR)
        endif

          write(lunW,*) '''OPTICS'''
          write(lunW,*) ' 1  all 0'

 711    continue
        read(lunR,fmt='(a)',end=721,err=721) txt300

        if(strcon(txt300,'''TWISS''',7,
     >                                       IS)) then 
C          skip
          read(lunR,fmt='(a)') txt300

        elseif(strcon(txt300,'''END''',5,
     >                               IS)
     >  .or. strcon(txt300,'''FIN''',5,
     >                               IS))   then 
          write(lunW,*) '''MATRIX'''
          write(lunW,*) ' 1  11'
          write(lunW,*) '''FAISCEAU'''
          write(lunW,*) '''END'''
          GOTO 721
        elseif(strcon(txt300,'''MATRIX''',8,
     >                                       IS)) then 
C          skip
          read(lunR,fmt='(a)',end=721,err=721) txt300
        elseif(strcon(txt300,'''FAISTORE''',10,
     >                                       IS)) then 
C          skip
          read(lunR,fmt='(a)',end=721,err=721) txt300
          read(lunR,fmt='(a)',end=721,err=721) txt300
        elseif(strcon(txt300,'''REBELOTE''',10,
     >                                         IS)) then 
C          skip
          read(lunR,fmt='(a)',end=721,err=721) txt300
        elseif(strcon(txt300,'stepSize',8,
     >                                        IS)) then 
          write(lunW,*) txtStep
        else
          write(lunW,*) txt300(debstr(txt300):finstr(txt300))   
        endif
      goto 711

 721  close(lunR)
      close(lunW)

Compute matrices so to draw various first order paramaters
      cmnd = 'cp -f zgoubi_searchCO-Out_BETA.dat zgoubi.dat'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
      write(*,*) '++++++ ',cmndZ
      call system(cmndZ)
      cmnd = 'cp -f zgoubi.res zgoubi_searchCO-Out_BETA.res'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
      cmnd = '~/zgoubi/struct/tools/betaFromMatrix/betaFromMatrix'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
C----------------------------------------------------

C----------------------------------------------------
      write(*,*) ' '
      write(*,*) '--------------------- '
      write(*,*) 'Track closed orbits, Dx, Dy'
      cmnd = 'rm -f  zgoubi.dat'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
      cmnd = 'cp -f zgoubi_searchCO-Out.dat zgoubi.dat'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
      write(*,*) '++++++ ',cmndZ
      call system(cmndZ)
      cmnd = 'rm -f  zgoubi_searchCO-Out.res'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
      cmnd = 'cp -f zgoubi.res zgoubi_searchCO-Out.res'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
      cmnd = '~/zgoubi/struct/tools/b_fai2Fai/fromBFai2Fai'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
      cmnd = 'rm -f zgoubi.fai'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
      cmnd = 'cp -f fromBFai2Fai.out  zgoubi.fai'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)
C Get Dx and Dy
      cmnd = '~/zgoubi/struct/tools/getDiffFromFai/getDiffFromFai'
      write(*,*) '++++++ ',cmnd
      call system(cmnd)

C Create gnuplots from tracking results
      cmmnd = '~/zgoubi/struct/tools/searchCO/geneGnuPlots'
      write(*,*) '---------------------------------------'
      write(*,*) cmmnd
      call system(cmmnd)

C Write a log_CO.tex file containing the plots above and create log_CO.pdf
      cmmnd = '~/zgoubi/struct/tools/searchCO/geneTexLog'
      write(*,*) '---------------------------------------'
      write(*,*) cmmnd
      call system(cmmnd)

cC View log_CO.pdf
c      cmmnd = 'okular ./Log_CO/log_CO.pdf'
c      write(*,*) '---------------------------------------'
c      write(*,*) cmmnd
c      call system(cmmnd)

      write(*,*) ' '
      write(*,*) 'Job "searchCO" ended, hopefully well... '
      write(*,*) ' '
      stop
      end
      FUNCTION STRCON(STR,STRIN,NCHAR,
     >                                IS)
      implicit double precision (a-h,o-z)
      LOGICAL STRCON
      CHARACTER STR*(*), STRIN*(*)
C     ------------------------------------------------------------------------
C     .TRUE. if the string STR contains the string STRIN with NCHAR characters
C     at least once.
C     IS = position of first occurence of STRIN in STR
C     ------------------------------------------------------------------------

      INTEGER DEBSTR,FINSTR

      II = 0
      DO 1 I = DEBSTR(STR), FINSTR(STR)
        II = II+1
        IF( STR(I:I+NCHAR-1) .EQ. STRIN ) THEN
          IS = II
          STRCON = .TRUE.
          RETURN
        ENDIF
 1    CONTINUE
      STRCON = .FALSE.
      RETURN
      END
      FUNCTION DEBSTR(STR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DEBSTR
      CHARACTER * (*) STR
C     -----------------------------------
C     Renvoie dans DEBSTR le rang du
C     premier caractere non-blanc de STR.
C     -----------------------------------
      DEBSTR=0
      LENGTH=LEN(STR)+1
1     CONTINUE
         DEBSTR=DEBSTR+1
         IF(DEBSTR.GE. LENGTH) RETURN
         IF (STR(DEBSTR:DEBSTR).EQ. ' ') GOTO 1
      RETURN
      END
      FUNCTION FINSTR(STRING)
      implicit double precision (a-h,o-z)
      INTEGER FINSTR
      CHARACTER * (*) STRING
C     --------------------------------------
C     RENVOIE DANS FINSTR LE RANG DU
C     DERNIER CHARACTER NON BLANC DE STRING,
C     OU BIEN 0 SI STRING EST VIDE ou BLANC.
C     --------------------------------------

      FINSTR=LEN(STRING)+1
1     CONTINUE
        FINSTR=FINSTR-1
        IF(FINSTR .EQ. 0) RETURN
        IF (STRING(FINSTR:FINSTR) .EQ. ' ') GOTO 1

      RETURN
      END
      subroutine avrorb(jo,maxIter,kaseV,cmndZ, 
     >                xav,xpav,zav,zpav,sav,d,tav,kex,ok,precX,precXp)
      implicit double precision (a-h,o-z)
      character(*) cmndZ
      logical existCO, convCO ,ok
      parameter (lunR=13,lunW=14)
      character txt300*300, let*1

      integer debstr, finstr
      character cmmnd*110
      logical strcon

      pi = 4.d0 * atan(1.d0)

      dx = 0.   !cm
      ddx = 0.1
      dxp = .0  ! mrad
      ddxp = 1.
      ddr = sqrt(ddx * ddx + ddxp * ddxp)
      iter = 1
      dz = 0.
      ddz = 0.1
      dzp = .0
      ddzp = 1.
      ddrz = sqrt(ddz * ddz + ddzp * ddzp)

c              write(*,*) ' avant getPUs '
c              read(*,*)
 2    continue

C Run zgoubi with single traj
      call system(cmndZ)

C Get initial Traj coord, and average orbit, from zgoubi.res
c              write(*,*) ' avant getPUs '
c              read(*,*)
      call getPUs_Av(
     >          x,xp,z,zp,s,d,t,let,xav,xpav,zav,zpav,sav,tav,kex)
      existCO = kex.eq.1
      if(existCO) then
        iter = 1
        write(6,*) 
        write(6,*) ' --------------------------------'
        write(6,*) ' -----  CO #',jo,' does exist...'
        write(6,*) ' --------------------------------'
        write(6,*)
        convCO = (abs(x-xav).le.precX) .and. (abs(xp-xpav).le.precXp) 
        if(kaseV.eq.2)
     >   convCO = convCO .and. 
     >     (abs(z-zav).le.precX) .and. (abs(zp-zpav).le.precXp) 
c        write(*,*) '  convergence : ',abs(x-xav), abs(xp-xpav)
c        write(*,*) '                ',abs(z-zav), abs(zp-zpav),convco
        if (convCO) then
          ok = .true.
          goto 99
        else
          write(6,fmt='(a,i6,a,1p,2e12.4,a)') 
     >    ' ------------ now seeking precision on CO #',jo,
     >    ',   precision dx, dx'' : ',precX,precXp,' cm, mrad'
          write(6,fmt='(2(a,I2))') '     iteration # ',iter,'/',maxIter
          write(6,*)
          xn = xav
          xpn = xpav 
          zn = zav
          zpn = zpav
          sn = s
        endif
      else
        write(6,*) ' '
        write(6,*) ' ------------------------------------------------'
        write(6,*) ' -----  Could not find CO #',jo,' trying again...'
        write(6,*) ' ------------------------------------------------'
        write(6,*) ' '
        write(6,fmt='(2(a,I2))') '        iteration # ',iter,'/',maxIter
        write(6,*)
        tta =  float(iter) * 2. * pi / 8.
        dx = float(iter) * ddr *cos(tta)
        xn = x + dx
        dxp = float(iter) * ddr *sin(tta)
        xpn = xp + dxp
        dz = float(iter) * ddrz *cos(tta)
        zn = z + dz
        dzp = float(iter) * ddrz *sin(tta)
        zpn = zp + dzp
        sn = s
      endif      
      call system('rm -f  searchCO.temp2')
      call system('cp -f zgoubi.dat searchCO.temp2')
      close(lunR)
      close(lunW)
      open(unit=lunR,file='searchCO.temp2')
      open(unit=lunW,file='zgoubi.dat')

C Read/write till "KOBJ"
        txt300 = ' '
        dowhile(
     >  .not. strcon(txt300(debstr(txt300):finstr(txt300)),'''OBJET''',
     >  7,IS)
     >  .and. 
     >  .not.strcon(txt300(debstr(txt300):finstr(txt300)),'''MCOBJET''',
     >  9,IS))
          read(lunR,fmt='(a)') txt300
          write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
c          write(*,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
c             read(*,*)
        enddo 
c        read(lunR,fmt='(a)') txt300
c        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
c        read(lunR,fmt='(a)') txt300
c        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))
        read(txt300,*) BORO
        !!!write(*,*) ' Reference rigidity BRho = ',BORO/1000.d0,' T.m' 
        read(lunR,*) XOBJ       
        write(lunW,fmt='(a)') '2'
        read(lunR,fmt='(a)') txt300
        write(lunW,fmt='(a)') '1  1'
C Write best co coordinates
        read(lunR,fmt='(a)') txt300
C        write(lunW,fmt='(1p,2e14.6,2e9.1,e9.1,e16.8,4a,i4)') 
        write(lunW,fmt='(1p,4e14.6,e9.1,e16.8,4a,i4)') 
     >    xn,xpn,zn,zpn,sn,d,' ','''',let,''' ',jo
C        write(*,fmt='(1p,a,2e14.6,2e9.1,e9.1,e16.8,4a,i4)') 
        write(*,fmt='(1p,a,4e14.6,e9.1,e16.8,4a,i4)') 
     >   ' New object : ', xn,xpn,zn,zpn,sn,d,' ','''','A','''',jo
C Completes zgoubi.dat with the rest of searchCO.temp2
 1    continue
        read(lunR,fmt='(a)',end=10) txt300
        write(lunW,fmt='(a)') txt300(debstr(txt300):finstr(txt300))   
      goto 1

 10   continue
      close(lunR)
      close(lunW)
      iter = iter+1
      if(iter.le.maxIter) then
         goto 2
      else
         ok = .false.
         goto 99
      endif

 99   continue
C      call system('rm searchCO.temp2')
      return
      end
      subroutine getPUs_Av(
     >        xn,xpn,zn,zpn,sn,dn,tn,let,xav,xpav,zav,zpav,sav,tav,kex)
      implicit double precision (a-h,o-z)
C Get initial Traj coord, and average orbit, from zgoubi.res
      character let*(*)
C Read pick-ups from last pass in zgoubi.res, and cumulates in readPU.out
C This software assumes use of REBELOTE with writes inhibited - so that PU readouts 
C are written in zgoubi.res at pass1 and last pass only. 

      character txt300*300

      logical strcon, pass1
      integer debstr, finstr
      data lunR / 15 /

      open(unit=lunR,file='zgoubi.res') 

      pass1 = .true.

 10   continue

      if(pass1) then
C Look for first trajectory. 
        read(lunR,*,end=18,err=19) txt300
        if(strcon(txt300,'OBJET',5,
     >                          IS)) then 
          read(lunR,*,end=18,err=19) txt300  
          write(*,*) txt300(debstr(txt300):finstr(txt300))
          read(lunR,*,end=18,err=19) txt300
          write(*,*) txt300(debstr(txt300):finstr(txt300))
          read(lunR,*,end=18,err=19) txt300
          write(*,*) txt300(debstr(txt300):finstr(txt300))
C Read trajectory
          read(lunR,*) xn,xpn,zn,zpn,sn,dn,let
c          write(*,*) '****** OBJET : ',xn,xpn,zn,zpn,sn,dn,' ',let
c              read(*,*)
        else
          goto 10
        endif
      endif

 12   continue
C On cherche 'PU_average'
      read(lunR,*,end=18,err=19) txt300
c      write(*,*) '                now txt300 is : ', txt300
      if(strcon(txt300,'PU_average',10,
     >                      IS)) then 
        if(pass1) then
          pass1=.false.
          goto 12
        else
          goto 11
        endif
      else
        goto 12
      endif

 11   continue
        write(6,*) ' Now reading PU contents, writing to readPU.out...'
        read(lunR,fmt='(a)',end=18,err=19) txt300   ! read a line of comments


C read units are :                 cm  mrd  cm  mrd  cm      mu_s
        read(lunR,fmt='(a)',end=18,err=19) txt300   ! read line of data 
        read(txt300,*,end=18,err=19) xav,xpav,zav,zpav,sav,dav,tav
c        write(*,*) txt300
c              read(*,*)

 90     continue
        write(6,*)  ' ' 
        write(6,*)  '----------' 
        write(*,*) '  Objet was : ',xn, xpn, zn, zpn, dn
        write(*,*) '  PU gives  : ',xav,xpav,zav,zpav,sav,dav,tav
        write(6,*)  ' ' 
        write(6,*)  ' ' 
        kex = 1
c             pause
      goto 99

 18   continue
      kex = 0
c      write(*,*) ' sbr getPUs * End of readPU upon EOFile *    '
      goto 99

 19   continue
      kex = 0
c      write(*,*) ' sbr getPUs * End of readPU upon read error *   '
 99   close(lunR)
      return
      end

      FUNCTION IDLUNI(LN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL IDLUNI

      LOGICAL OPN

      I = 20
 1    CONTINUE
        INQUIRE(UNIT=I,ERR=99,IOSTAT=IOS,OPENED=OPN)
        I = I+1
        IF(I .EQ. 100) GOTO 99
        IF(OPN) GOTO 1
        IF(IOS .GT. 0) GOTO 1
      
      LN = I-1
      IDLUNI = .TRUE.
      RETURN

 99   CONTINUE
      LN = 0
      IDLUNI = .FALSE.
      RETURN
      END
      subroutine readat(lunIn,fname,
     >                              kaseV,ierr)
      implicit double precision (a-h,o-z)

      include "READAT.H"

      return
      end

      FUNCTION EMPTY(STR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL EMPTY
      CHARACTER*(*) STR
C     -----------------------------------------------------
C     .TRUE. if STR is either empty or contains only blanks
C     -----------------------------------------------------

      INTEGER FINSTR
      EMPTY = FINSTR(STR) .EQ. 0
      RETURN
      END
