      COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
     >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
 
C zgoubi/block.f:       COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/fborne.f:      COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/ff.f:          COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/fitarr.f:      COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/fitest.f:      COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/fitnu.f:       COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/impctr.f:      COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/impvar.f:      COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/rempli.f:      COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/rfit.f:        COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/vrble.f:       COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),
C zgoubi/block.f:       COMMON/VARY/ NV,IR(MXV),NC,I1(MXV),I2(MXV),V(MXV),IS(MXV),W(MXV),

C zgoubi/block.f-     >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
C zgoubi/fborne.f-    >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
C zgoubi/ff.f-        >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
C zgoubi/fitarr.f-    >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
C zgoubi/fitest.f-    >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
C zgoubi/fitnu.f-     >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
C zgoubi/impctr.f-    >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
C zgoubi/impvar.f-    >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
C zgoubi/rempli.f-    >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
C zgoubi/rfit.f-      >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
C zgoubi/vrble.f-     >IC(MXV),IC2(MXV),I3(MXV),XCOU(MXV),CPAR(MXV,27)
