Data generated by searchCO                                                                                    
 'OBJET'                                                                                                      1
7136.9707     reference rigidity (kG.cm),  G.gamma =             4.4642                                       
2                                                                                                             
1  1                                                                                                          
4.765493E-05  5.666187E-05  0.000000E+00  0.000000E+00  0.0E+00  1.00000000E+00 'o'      1398.03 MeV          
1                                                                                                             
 'FAISCEAU'                                                                                                   2
 'FAISTORE'                                                                                                   3
b_zgoubi.fai  all                                                                                             
1                                                                                                             
 'MARKER'     #Start                                                                                          4
 'PARTICUL'                                                                                                   5
9.3827203E+02   1.6021765E-19  1.7928474 0 0                                                                  
 'FAISCEAU'                                                                                                   6
 'MARKER'     #End                                                                                            7
 'REBELOTE'                                                                                                   8
0   0.2  99                                                                                                   
 'END'                                                                                                        9

************************************************************************************************************************************
      1  Keyword, label(s) :  OBJET                             

                          MAGNETIC  RIGIDITY =       7136.971 kG*cm

                                         CALCUL  DES  TRAJECTOIRES

                              OBJET  (2)  FORME  DE      1 POINTS 



************************************************************************************************************************************
      2  Keyword, label(s) :  FAISCEAU                          

0                                             TRACE DU FAISCEAU

                                                1 TRAJECTOIRES

                                   OBJET                                                  FAISCEAU

          D       Y(CM)     T(MR)     Z(CM)     P(MR)    S(CM)          D       Y(CM)     T(MR)     Z(CM)     P(MR)    S(CM)

o   1   1.0000     0.000     0.000     0.000     0.000     0.000       1.0000    0.000    0.000    0.000    0.000        0.000     1


  Beam  characteristics   (EMIT,ALP,BET,XM,XPM,NLIV,NINL,RATIN) : 

    0.000        0.000        0.000       4.7655E-07   5.6662E-08       1       0    0.000    B-Dim     1      1
    0.000        0.000        0.000        0.000        0.000           1       0    0.000    B-Dim     2      1
    0.000        0.000        0.000        0.000        2140.           1       0    0.000    B-Dim     3      1


  Beam  characteristics   SIGMA(4,4) : 

           Ex, Ez =  0.000000E+00  0.000000E+00
           AlpX, BetX =           NaN           NaN
           AlpZ, BetZ =           NaN           NaN

  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00

  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00

  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00

  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00

************************************************************************************************************************************
      3  Keyword, label(s) :  FAISTORE                          


                OPEN FILE b_zgoubi.fai                                                                    
                FOR PRINTING COORDINATES 

               Print will occur at element[s] labeled : 
                    all       

************************************************************************************************************************************
      4  Keyword, label(s) :  MARKER      #Start                


************************************************************************************************************************************
      5  Keyword, label(s) :  PARTICUL                          


     Particle  properties :

                     Mass          =    938.272        MeV/c2
                     Charge        =   1.602176E-19    C     
                     G  factor     =    1.79285              

              Reference  data :
                    mag. rigidity (kG.cm)   :   7136.9707      =p/q, such that dev.=B*L/rigidity
                    mass (MeV/c2)           :   938.27203    
                    momentum (MeV/c)        :   2139.6100    
                    energy, total (MeV)     :   2336.2974    
                    energy, kinetic (MeV)   :   1398.0253    
                    beta = v/c              :  0.9158123609    
                    gamma                   :   2.490000012    
                    beta*gamma              :   2.280372789    
                    G*gamma                 :   4.464190047    
                    electric rigidity (MeV) :   1959.481307      =T[eV]*(gamma+1)/gamma, such that dev.=E*L/rigidity
  
 I, AMQ(1,I), AMQ(2,I)/QE, P/Pref, v/c, time :
  
     1   9.38272030E+02  1.00000001E+00  1.00000000E+00  9.15812361E-01  0.00000000E+00

************************************************************************************************************************************
      6  Keyword, label(s) :  FAISCEAU                          

0                                             TRACE DU FAISCEAU

                                                1 TRAJECTOIRES

                                   OBJET                                                  FAISCEAU

          D       Y(CM)     T(MR)     Z(CM)     P(MR)    S(CM)          D       Y(CM)     T(MR)     Z(CM)     P(MR)    S(CM)

o   1   1.0000     0.000     0.000     0.000     0.000     0.000       1.0000    0.000    0.000    0.000    0.000        0.000     1
               Time of flight (mus) :   0.0000000     mass (MeV/c2) :   938.272    


  Beam  characteristics   (EMIT,ALP,BET,XM,XPM,NLIV,NINL,RATIN) : 

    0.000        0.000        0.000       4.7655E-07   5.6662E-08       1       0    0.000    B-Dim     1      1
    0.000        0.000        0.000        0.000        0.000           1       0    0.000    B-Dim     2      1
    0.000        0.000        0.000        0.000        1398.           1       0    0.000    B-Dim     3      1


  Beam  characteristics   SIGMA(4,4) : 

           Ex, Ez =  0.000000E+00  0.000000E+00
           AlpX, BetX =           NaN           NaN
           AlpZ, BetZ =           NaN           NaN

  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00

  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00

  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00

  0.000000E+00  0.000000E+00  0.000000E+00  0.000000E+00

************************************************************************************************************************************
      7  Keyword, label(s) :  MARKER      #End                  


************************************************************************************************************************************
      8  Keyword, label(s) :  REBELOTE                          


                         ****  End  of  'REBELOTE'  procedure  ****

      There  has  been          1  passes  through  the  optical  structure 

                     Total of          1 particles have been launched

************************************************************************************************************************************
      9  Keyword, label(s) :  END                               


                             1 particles have been launched
                     Made  it  to  the  end :      1

************************************************************************************************************************************

           MAIN PROGRAM : Execution ended upon key  END       

************************************************************************************************************************************
   
            Zgoubi run completed. 

  Zgoubi, version 5.1.0.
  Job  started  on  13/10/12 ,  at  13:34:52 
  Job  ended  on    13/10/12 ,  at  13:34:52 

   CPU time, total :    1.600100000000000E-002
