INC=../include

OBJ=\
 accen.o\
 accep.o\
 adpol.o\
 aimant.o\
 apdpo1.o\
 apdpo.o\
 apherf.o\
 autorf.o\
 avorpr.o\
 bar2xy.o\
 baxbxr.o\
 beaimp.o\
 beamat.o\
 bendf.o\
 bendi.o\
 binari.o\
 binary.o\
 block.o\
 bonul.o\
 boost.o\
 butee.o\
 bxrxyz.o\
 carla.o\
 carshi.o\
 cavite.o\
 chamb.o\
 chamc.o\
 chamk.o\
 charef.o\
 chmbre.o\
 chmbr.o\
 chrefe.o\
 chreg.o\
 chxc.o\
 chxp.o\
 cible.o\
 cinema.o\
 cntinl.o\
 cntpar.o\
 coeffs.o\
 cofin.o\
 coils.o\
 coilsf.o\
 collim.o\
 cptfct.o\
 csri.o\
 csrint.o\
 ctrlb.o\
 ctrlc.o\
 cubspl.o\
 dbdxyz.o\
 debstr.o\
 dejaca.o\
 delta.o\
 depla.o\
 desbin.o\
 devtra.o\
 dipi.o\
 dipolm.o\
 dipsi.o\
 dist2.o\
 dpkick.o\
 drtent.o\
 drvg.o\
 dstefb.o\
 eax3tu.o\
 eaxial.o\
 el2tub.o\
 el2tu.o\
 elcmid.o\
 elcmif.o\
 elcmii.o\
 elcyld.o\
 elcyl.o\
 ellip.o\
 elmirf.o\
 elmiri.o\
 emmac.o\
 emmap.o\
 end.o\
 endfit.o\
 endjob.o\
 enrgy.o\
 ererz.o\
 erexyz.o\
 erzxyz.o\
 esl.o\
 eslvir.o\
 event.o\
 fborne.o\
 ffagi.o\
 ff.o\
 ffgspi.o\
 ffspd.o\
 fgf.o\
 finstr.o\
 fitarr.o\
 fitest.o\
 fitexp.o\
 fitgtv.o\
 fitlav.o\
 fitlma.o\
 fitmm.o\
 fitnu.o\
 fitset.o\
 fitsta.o\
 flush2.o\
 fmapw.o\
 focal1.o\
 focale.o\
 funcd.o\
 gammln.o\
 gang.o\
 gascat.o\
 gasesl.o\
 gasini.o\
 geneta.o\
 getnam.o\
 getdst.o\
 gg.o\
 header.o\
 helix.o\
 helixf.o\
 histab.o\
 hist.o\
 icentr.o\
 idlg.o\
 idluni.o\
 ifmes.o\
 impaju.o\
 impcsr.o\
 impctr.o\
 impdev.o\
 impfai.o\
 impplt.o\
 imptra.o\
 impvar.o\
 inicin.o\
 inidrt.o\
 initra.o\
 integr.o\
 interm.o\
 interv.o\
 intplf.o\
 itavan.o\
 iter.o\
 itsens.o\
 jcentr.o\
 krtax.o\
 kstop.o\
 lign.o\
 lingua.o\
 lnul.o\
 lpsfit.o\
 lpsfi4.o\
 lstins.o\
 lstset.o\
 majtra.o\
 mapshf.o\
 maplim.o\
 mat1.o\
 mat2.o\
 matimp.o\
 matric.o\
 mcdes.o\
 mcdesi.o\
 mcdesl.o\
 mcobj1.o\
 mcobj3.o\
 mcobj.o\
 mino1.o\
 minonm.o\
 mix.o\
 mksa.o\
 modord.o\
 multip.o\
 multpo.o\
 nmfonc.o\
 nmmin1.o\
 nmmin.o\
 normal.o\
 normb.o\
 obj3.o\
 obj5.o\
 obj6.o\
 obj8.o\
 objerr.o\
 objeta.o\
 objets.o\
 objtrk.o\
 okkt.o\
 open2.o\
 partic.o\
 path.o\
 pavel.o\
 pckup.o\
 pickup.o\
 pltdat.o\
 poidev.o\
 polmes.o\
 prdata.o\
 pscal.o\
 pvect.o\
 quasex.o\
 raiman.o\
 rautor.o\
 raysyn.o\
 razdrv.o\
 rbend.o\
 rbinar.o\
 rcarte.o\
 rcavit.o\
 rcible.o\
 rcoils.o\
 rcolli.o\
 rcsr.o\
 rdip.o\
 rdips.o\
 rdpois.o\
 rebel.o\
 rebmul.o\
 refer.o\
 rel2tu.o\
 relcmi.o\
 relcyl.o\
 relmir.o\
 remma.o\
 rempli.o\
 reset.o\
 rfaist.o\
 rffags.o\
 rfit.o\
 rfitgt.o\
 rgasca.o\
 rhelix.o\
 rmcdes.o\
 rmcobj.o\
 rmulti.o\
 rnorma.o\
 robjet.o\
 robjta.o\
 rotx.o\
 rparti.o\
 rpckup.o\
 rqsod.o\
 rscal.o\
 rsepar.o\
 rsimb.o\
 rsolen.o\
 rspn.o\
 rsrlos.o\
 rtnewt.o\
 rtrans.o\
 rundul.o\
 runipo.o\
 rwienf.o\
 scal0.o\
 scaler.o\
 scalin.o\
 scumul.o\
 separa.o\
 serv2.o\
 serv32.o\
 serv34.o\
 serv4.o\
 serv5.o\
 settim.o\
 solenf.o\
 soleno.o\
 solv.o\
 splint.o\
 spn.o\
 spnprn.o\
 spnprt.o\
 spnrot.o\
 spntrk.o\
 sref.o\
 srloss.o\
 srprn.o\
 stpsiz.o\
 straco.o\
 symmed.o\
 sympl.o\
 synpar.o\
 syntrk.o\
 toroid.o\
 toscac.o\
 toscap.o\
 trace.o\
 track.o\
 transf.o\
 transm.o\
 traobj.o\
 trarot.o\
 trbeam.o\
 tridi.o\
 trobj.o\
 trrote.o\
 tunes.o\
 twiss.o\
 undulfa.o\
 undulf.o\
 undulia.o\
 unduli.o\
 unipo.o\
 unipot.o\
 valqv.o\
 vequal.o\
 vrble.o\
 vscal.o\
 vzero.o\
 waist.o\
 wedgki.o\
 wienfi.o\
 xnorm.o\
 xrotb.o\
 ymoiny.o\
 zerof.o\
 zgoubi.o\
 zgoubi_main.o

.POSIX:

.f.o:
	$(FC) $(FFLAGS) -I$(INC) -c $<

zgoubi : $(OBJ)
	$(FC) $(LDFLAGS) $(OBJ) -L../common -lzg -o $@

clean :
	$(RM) *.o zgoubi *~

accen.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
accep.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
aimant.o: $(INC)/MXLD.H $(INC)/MAXCOO.H
autorf.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
bendi.o: $(INC)/MXLD.H
binary.o: $(INC)/MXLD.H
block.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H $(INC)/MXFS.H
bonul.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H
carla.o: PARIZ.H $(INC)/MAXTRA.H $(INC)/MXLD.H
carshi.o: PARIZ.H $(INC)/MXLD.H
cavite.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H $(INC)/MXFS.H
chamb.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
chamc.o: $(INC)/MAXTRA.H
chamk.o: PARIZ.H $(INC)/MAXTRA.H
charef.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
chmbre.o: $(INC)/MAXTRA.H
chmbr.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
chrefe.o: $(INC)/MAXTRA.H $(INC)/MXSTEP.H CSR.H $(INC)/MXLD.H $(INC)/MAXCOO.H
chxc.o: PARIZ.H $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MXFS.H $(INC)/FILPLT.H
chxp.o: PARIZ.H $(INC)/MXLD.H $(INC)/MXFS.H $(INC)/FILPLT.H
cible.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H $(INC)/MXLD.H
cntinl.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H
coeffs.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
cofin.o: $(INC)/MAXTRA.H $(INC)/MXSTEP.H CSR.H $(INC)/MAXCOO.H
coils.o: $(INC)/MXLD.H
collim.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
csri.o: $(INC)/MXSTEP.H $(INC)/MAXTRA.H CSR.H $(INC)/MXLD.H $(INC)/MAXCOO.H
csrint.o: $(INC)/MXSTEP.H $(INC)/MAXTRA.H CSR.H $(INC)/MAXCOO.H
dejaca.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
dipi.o: $(INC)/MXLD.H
dipolm.o: PARIZ.H $(INC)/MAXTRA.H $(INC)/MXLD.H
dipsi.o: $(INC)/MXLD.H
dist2.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
dpkick.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MXFS.H
el2tub.o: $(INC)/MXLD.H
elcmii.o: $(INC)/MXLD.H
elcyld.o: $(INC)/MXLD.H
elmiri.o: $(INC)/MXLD.H
end.o: $(INC)/MXSTEP.H $(INC)/MAXTRA.H CSR.H $(INC)/MAXCOO.H
endfit.o: $(INC)/MXLD.H
esl.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
eslvir.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
event.o: $(INC)/MAXTRA.H
fborne.o: $(INC)/MXLD.H
ffagi.o: $(INC)/MXLD.H
ff.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
ffgspi.o: $(INC)/MXLD.H
fitarr.o: $(INC)/MXLD.H
fitest.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H $(INC)/MXLD.H
fitgtv.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
fitlav.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H
fitlma.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H
fitnu.o: $(INC)/MXLD.H
fitset.o: $(INC)/MXLD.H
fmapw.o: PARIZ.H
focal1.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
focale.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H
gascat.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
gasesl.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
gasini.o: $(INC)/MXLD.H
helix.o: $(INC)/MXLD.H
hist.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
icentr.o: PARIZ.H
impcsr.o: $(INC)/MAXTRA.H $(INC)/MXSTEP.H CSR.H $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MXFS.H
impdev.o: $(INC)/MAXTRA.H
impfai.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H $(INC)/FRMFAI.H
impplt.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MXFS.H $(INC)/FRMPLT.H
imptra.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
impvar.o: $(INC)/MXLD.H
inidrt.o: $(INC)/MXLD.H
initra.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
integr.o: $(INC)/MXSTEP.H
intplf.o: $(INC)/MAXTRA.H
jcentr.o: PARIZ.H
krtax.o: PARIZ.H
kstop.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MXFS.H
lign.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
lpsfit.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H
majtra.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H
mat1.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
mat2.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H
matimp.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H
matric.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H
mcdes.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
mcdesi.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
mcdesl.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
mcobj1.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
mcobj3.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
mcobj.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
mix.o: $(INC)/MAXCOO.H
mksa.o: $(INC)/MAXCOO.H
modord.o: $(INC)/MXLD.H
multip.o: $(INC)/MAXTRA.H
multpo.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MXFS.H
normal.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H
obj3.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/FRMFAI.H
obj5.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
obj6.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
obj8.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
objeta.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
objets.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
objtrk.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
okkt.o: $(INC)/OKKT.H
partic.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H
path.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
pavel.o: PARIZ.H
pckup.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
pltdat.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H
polmes.o: PARIZ.H $(INC)/MXLD.H
prdata.o: $(INC)/MXLD.H
quasex.o: $(INC)/MXLD.H $(INC)/MAXCOO.H
rautor.o: $(INC)/MXLD.H
raysyn.o: $(INC)/MXLD.H $(INC)/MXFS.H $(INC)/MAXTRA.H
rbend.o: $(INC)/MXLD.H
rbinar.o: $(INC)/MXLD.H
rcarte.o: $(INC)/MXLD.H
rcavit.o: $(INC)/MXLD.H
rcible.o: $(INC)/MXLD.H
rcolli.o: $(INC)/MXLD.H
rcsr.o: $(INC)/MXLD.H
rdip.o: $(INC)/MXLD.H
rdips.o: $(INC)/MXLD.H
rebel.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
rebmul.o: $(INC)/MXLD.H
refer.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H
rel2tu.o: $(INC)/MXLD.H
relcmi.o: $(INC)/MXLD.H        
relcyl.o: $(INC)/MXLD.H
relmir.o: $(INC)/MXLD.H        
rempli.o: $(INC)/MXLD.H
reset.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H $(INC)/MXFS.H
rfaist.o: $(INC)/MXLD.H
rffags.o: $(INC)/MXLD.H
rfit.o: $(INC)/MXLD.H
rfitgt.o: $(INC)/MXLD.H
rgasca.o: $(INC)/MXLD.H
rhelix.o: $(INC)/MXLD.H
rmcdes.o: $(INC)/MXLD.H
rmcobj.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
rnorma.o: $(INC)/MXLD.H
robjet.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
robjta.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H
rparti.o: $(INC)/MXLD.H
rscal.o: $(INC)/MXLD.H $(INC)/MXFS.H
rsepar.o: $(INC)/MXLD.H
rsimb.o: $(INC)/MXLD.H
rspn.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H
rsrlos.o: $(INC)/MXLD.H
rtrans.o: $(INC)/MXLD.H
rundul.o: $(INC)/MXLD.H
runipo.o: $(INC)/MXLD.H
rwienf.o: $(INC)/MXLD.H        
scaler.o: $(INC)/MXFS.H $(INC)/MXLD.H
scalin.o: $(INC)/MXLD.H $(INC)/MXFS.H
scumul.o: $(INC)/MAXCOO.H
separa.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
serv2.o: PARIZ.H
serv32.o: PARIZ.H
serv34.o: PARIZ.H
serv4.o: PARIZ.H
serv5.o: PARIZ.H
settim.o: $(INC)/MAXCOO.H $(INC)/MAXTRA.H
soleno.o: $(INC)/MXLD.H
spn.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H
spnprn.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H
spnprt.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
spnrot.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
spntrk.o: $(INC)/MAXTRA.H
sref.o: $(INC)/MXSTEP.H $(INC)/MAXTRA.H CSR.H $(INC)/MAXCOO.H
srloss.o: $(INC)/MXLD.H
srprn.o: $(INC)/MXLD.H
stpsiz.o: $(INC)/MXLD.H
synpar.o: $(INC)/MXLD.H
toroid.o: $(INC)/MAXTRA.H
toscac.o: PARIZ.H $(INC)/MAXTRA.H $(INC)/MXLD.H
toscap.o: PARIZ.H $(INC)/MAXTRA.H $(INC)/MXLD.H
trace.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
track.o: $(INC)/MXLD.H
transf.o: $(INC)/MAXTRA.H $(INC)/MXSTEP.H CSR.H $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MXFS.H
transm.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
traobj.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
trarot.o: $(INC)/MAXTRA.H $(INC)/MXSTEP.H CSR.H $(INC)/MXLD.H $(INC)/MAXCOO.H
trbeam.o: $(INC)/MXLD.H $(INC)/MXFS.H
trobj.o: $(INC)/MAXTRA.H $(INC)/MXLD.H $(INC)/MAXCOO.H
trrote.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
twiss.o: $(INC)/MXLD.H $(INC)/MAXCOO.H $(INC)/MAXTRA.H
undulia.o: $(INC)/MXLD.H
unduli.o: $(INC)/MXLD.H
unipot.o: $(INC)/MXLD.H
waist.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
wedgki.o: $(INC)/MAXCOO.H
wienfi.o: $(INC)/MXLD.H
ymoiny.o: $(INC)/MAXTRA.H $(INC)/MAXCOO.H
zgoubi.o: $(INC)/MXLD.H $(INC)/MAXTRA.H $(INC)/MAXCOO.H $(INC)/MXFS.H PARIZ.H $(INC)/FILPLT.H $(INC)/LSTKEY.H
zgoubi_main.o: $(INC)/MXLD.H
